### ISSUE TITLE
/users endpoint needs search, filters, and paging options to support a community page

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-server#100]
The first version of the community page (genome/civic-client#255) will mainly be a user list with the ability to search and filter users, so in order to provide those features the client will need search, filters, and paging on the /users endpoint.

**Comment by jmcmichael** [comment]
Or maybe user search should be at /users/search to remain consistent with evidence item search?

**Comment by acoffman** [comment]
Done.
