### ISSUE TITLE
Use a sequence ontology to define variant types

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#102]
Lynzey has investigated using/developing a sequence ontology (SO) based on the [Sequence Ontology](http://www.sequenceontology.org/).  The idea would be to have a `variant type` and to constrain the choices to those that are valid in the SO similar to what we do for disease and gene names now.

Schema she produced is provided as a PDF here (with a screenshot below):

[Sequence Ontology for CIViC.pdf](https://github.com/genome/civic-server/files/28271/Sequence.Ontology.for.CIViC.pdf)

Her notes:
> I believe Sequence Ontology will help when organizing all the variants in CIViC. Attached is the Sequence Ontology I formed. Displayed are the most common variants in CIViC. These variants are in the red boxes.  As a source I used the MISO Sequence Ontology Browser.

> At first I listed all the variants in CIViC, and then I looked at which were the most common. Therefore, the only variants in the Sequence Ontology currently are the most common ones. Putting all the variants in the Sequence Ontology might get too cluttered and be inefficient to the user. To solve this issue, we could maybe have the user type in the variant they are searching for, and despite it not appearing on the actual Sequence Ontology, it could illustrate where it would be.

> For the illustrated Sequence Ontology, I also eliminated the many children of some variants in order to better visualize the entire ontology. We could potentially do the same thing where the user types in the variant they are looking for, and if doesn’t appear on the ontology, it could illustrate where it would be.

> Some problems I ran into were with the variants Overexpression, Expression, and Underexpression. These terms were not in the Sequence Ontology Browser. I sent a ticket in, in which they responded that it could not be defined with Sequence Ontology. This is due to the fact that it is dependent on the genotype, environment, and management/experiment-setup.

![civic-proposedseqontology](https://cloud.githubusercontent.com/assets/856728/10976537/f6f4ab56-83b1-11e5-9c7c-508ba3ad392b.png)

**Comment by malachig** [comment]
Okay, KK and I just reviewed this again.  Bottomline is that the Sequence Ontology looks very promising!  I think we should move forward with this.  We even found that the RNA related variants (fusion, over-expression, etc.) are supported.

Proposed steps to proceed:

1.) Obtain a slice of the SO. Basically we want everything under (all children) of `sequence_variant` (http://www.sequenceontology.org/browser/current_svn/term/SO:0001060).

2.) Update the schema to allow each CIViC variant to be associated with *one or more* SO terms.

3.) Update the variant edit form to allow *one or more* SO terms to be associated with the variant (similar to the add drugs function in evidence items).  Use typeahead to present the user with possible option.

4.) In the variant summary section, display the SO terms and link them out to that record in the SO like so: http://www.sequenceontology.org/browser/current_svn/term/SO:0001586

**Comment by acoffman** [comment]
This is complete so I'm going to go ahead and close it. I'm going to leave #178 open though as I don't know if the discussion around importing other branches of the ontology is resolved yet.
