### ISSUE TITLE
Add variant ID to 'utilities' -> 'merge variants' in admin interface

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#109]
One of the use cases for merging variants is where we have inadvertently created two variants, each with a set of evidence items but the variants are duplicates.  Sometimes even the name is an exact match.  When the variant names are identical, it is hard to tell which to "keep" in the merge action of the admin interface.

This could be made unambiguous by displaying the IDs of the entities to be merged along with the variant name and gene name that are currently shown.  

Overall this utility is working nicely and is very helpful!

**Comment by acoffman** [comment]
Added in master!
