### ISSUE TITLE
Unable to change gene associated with a variant

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#110]
This variant is currently associated with FGFR3 (gene 23)
https://civic.genome.wustl.edu/admin/variants/54

It should be associated with FGFR2 (gene 22).  The admin interface allows us to edit the variant and make this change.  It then reports that the variant has been updated successfully, but the variant is still associated with FGFR3 (gene 23).  Tried it twice to be sure that we were not going crazy. :)

**Comment by acoffman** [comment]
Fixed in master! Will go out in next deploy.
