### ISSUE TITLE
migrate ensembl version from rep transcript field to ensembl version field

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#114]
Hi @acoffman 

We talked about this in the last meeting but here is an issue for tracking. Can we migrate ensembl version information, now stored as part of the representative transcript field to the new dedicated ensembl version field.

Right now we have followed the convention of storing it in the representative transcript field like this: `ENST00000275493.2 (v75)`.  We want the `75` part to go to the Ensembl version field and drop the ` (v75)` from the representative transcript field.

**Comment by acoffman** [comment]
Definitely! This shouldn't be difficult to do - just a quick regex.

**Comment by acoffman** [comment]
This is complete and in production!
