### ISSUE TITLE
Database and community statistics are not all up to date?

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#115]
The Database and Community Statistics on the CIViC landing page mostly seem to make sense.  Except for Genes and Variants.  These don't seem to update.  For example, there is a recent new gene and variant for BIRC7:

https://civic.genome.wustl.edu/#/events/genes/14842/summary/variants/251/summary

that does not seem to be represented in the current stats.

<img width="413" alt="screen shot 2015-12-03 at 12 08 09 pm" src="https://cloud.githubusercontent.com/assets/856728/11569265/917c176c-99b6-11e5-8641-09494ee74463.png">

**Comment by acoffman** [comment]
This is now fixed in master!
