### ISSUE TITLE
Add a new type for `variant origin` in the database schema

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#117]
Background:

Currently, only two values are allowed for the `variant origin` value of each evidence item.  `variant origin` refers to the genetic/genomic classification of the variant that an evidence item refers to.  Currently, this can be `somatic` or `germline`.  In both cases, we were mostly thinking about **mutation**.  A somatic mutation exists only in the tumor cells.  A germline mutation is present in every cell of the individual but is still a mutation in the sense that is not common in the human population.  Germline mutations in this sense were either acquired at a very early stage of development, or during gametogenesis, or were acquired by an immediate family member and passed on to the proband in question (i.e. a feature of that family, not the population at large).  Note that if the origin was during an early stage of development the result is somatic mosaicism.  Should the schema be able to support that as well.  In some cases, the mosaicism itself is clinically relevant.

Recent submissions to CIViC have reminded us that users may be interested in "common" polymorphisms that are clinically significant.  The definition of common may vary.  It may still be rare in the population at large (e.g. 1-5%) but far more common than the mutations above.  Many things about the way we think about these types of variants will be different from the mutations described above.  For example, the types of studies that describe them may involve use of *association* methods that are generally not possible for rare germline mutations and somatic mutations.  While we have been focused on somatic/germline mutations, there is a large community out there that is focused much more on polymorphism and there is a huge amount of extant data of this type.

@acoffman to distinguish the three classes I propose having three options in the schema:
`somatic` (or `somatic mutation`)
`germline` (or `germline mutation`)
`polymorphism` (or `germline polymorphism`)

We should agree on these three names before proceeding. There has already been some debate.  For example, `germline rare variant` was proposed instead of `polymorphism`.  `common polymorphism` is another option.

We need to have a separate discussion on how to decide which polymorphisms are acceptable in CIViC.  Our goal is not to reproduce PharmGKB or ClinVar which already have a pretty good handle on polymorphisms.  We should be quite particular about what polymorphisms are allowed in CIViC.  They must have a well articulated clinical significance just like anything else in CIViC, but for polymorphisms we may want to set the bar even higher. We need to generate guidelines that help curators decide which polymorphisms are CIViC worthy.

@jmcmichael once we have decided on this as a group, I guess we will need to update a few things in the front end. e.g. 
- the drop down menu when creating an evidence item (and associated documentation beside this menu)
- we will need a third symbol to accompany this new value in the evidence item data grid
- the legend will need to be updated to explain the meaning of this third symbol for `variant origin`

**Comment by obigriffith** [comment]
+1 for the slightly more verbose options: somatic mutation, germline mutation or germline polymorphism.

**Comment by malachig** [comment]
@acoffman and @jmcmichael can we go ahead with these values: 

`somatic mutation` -> everything that is currently `somatic`
`germline mutation` -> everything that is currently `germline`
`germline polymorphism` -> a new value that we will start to assign to certain evidence items.

Figuring out which evidence items need to be changed from `germline mutation` to `germline polymorphism` will be a curation task but should not be too hard because there are not too many of these yet.

**Comment by acoffman** [comment]
Cool, I'll go ahead and make the change!

**Comment by malachig** [comment]
@acoffman , here is the final, final choice.  Can we get these added to the options available for `variant origin`?

`somatic mutation` -> everything that is currently `somatic`
`germline mutation` -> everything that is currently `germline`
`germline polymorphism` -> a new value that we will start to assign to certain evidence items.
`unknown` -> a new value that we will start to assign to certain evidence items.
`n/a` -> a new value that we will start to assign to certain evidence items.

**Comment by acoffman** [comment]
Yup, I'll coordinate with @jmcmichael and we'll get these updated this week!

**Comment by acoffman** [comment]
I have pushed both front and back end changes to facilitate this, and its working in all the grid views, add evidence form, and legend/key.

Like in #139, I have picked icons that seemed appropriate (https://getbootstrap.com/components/) but we can change them to whatever you guys prefer.

Additionally, I was unsure of what you wanted the definitions and tooltip/help text for these new variant origin values to say, so I have added them in their appropriate places in the client repo with `FIXME` as the values. I'll go ahead and leave this issue open until we come up with those definitions!

**Comment by obigriffith** [comment]
How about something along these lines. Note, even existing definitions will need to be updated to reflect the new scheme.

'Somatic Mutation': 'Variant is a mutation, found only in tumor cells, having arisen in a specific tissue (non-germ cell), and is not expected to be inherited or passed to offspring',
'Germline Mutation': 'Variant is a mutation, found in every cell, not restricted to tumor/diseased cells, is expected to have arisen de novo in the germ cells responsible for the current generation or only very recent generations (e.g., close family members), and is not thought to exist in the population at large',
'Germline Polymorphism': 'Variant is found in every cell, not restricted to tumor/diseased cells, and thought to represent common (or relatively rare) variation in the population at large',
'Unknown': 'The variant origin is uncertain based on the available evidence',
'N/A': 'The variant type (e.g., expression) is not compatible (or easily classified) with the CIViC concepts of variant origin',

**Comment by malachig** [comment]
These sound great to me.

**Comment by acoffman** [comment]
New definitions added and pushed to master in the client repo!
