### ISSUE TITLE
Error 500 on attempt to accept revision

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#123]
I get an error when I attempt to accept this revision:

https://civic.genome.wustl.edu/#/events/genes/1885/summary/variants/268/summary/evidence/681/talk/revisions/list/479/summary#evidence

Not sure if it is related, but this is a case where a new evidence item was submitted, and then a revision was proposed by the same user before it had been accepted.  I accepted the evidence item itself, but I am not able to accept the subsequent revision...

**Comment by acoffman** [comment]
Looks like yesterday's deploy inadvertently contained a commit that wasn't ready to go out just yet. I've hotfixed it and was able to accept the revision successfully. Sorry about that!

**Comment by malachig** [comment]
Thanks!
