### ISSUE TITLE
Missing disease ontology terms in live site

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#124]
A user reported a problem entering a disease for this Evidence Item:
https://civic.genome.wustl.edu/#/events/genes/37/summary/variants/294/summary/evidence/739/summary#evidence

The disease is `Merkel cell carcinoma` which is the Disease Ontology as `DOID:3965`.  This entry does not appear to be available in CIViC.  

Is this true @acoffman ?  Is it actually missing?  Or are we just having an issue with the drop down options perhaps?

We should remember to fix this evidence item as soon as we are able to.

**Comment by acoffman** [comment]
@malachig this is the same issue as #118. This disease is not in the cancer specific Disease Ontology dump. I believe that our decision from the last meeting was to continue to use the cancer-only subset to create our mirror, but to open issues with disease ontology where obvious cancers were missing (https://github.com/DiseaseOntology/HumanDiseaseOntology/issues).

In the mean time, I have manually added this particular disease and it now appears as an option in the dropdowns and forms.

**Comment by acoffman** [comment]
@malachig I've opened DiseaseOntology/HumanDiseaseOntology#116 to inquire about the inclusion of these diseases.

**Comment by malachig** [comment]
Oh I see. That is interesting. The viewer shows it pretty clearly as falling under the cancer umbrella. I'm curious to see what they say to your query. 
![screen shot 2015-12-22 at 4 34 16 pm](https://cloud.githubusercontent.com/assets/856728/11967647/25d48256-a8ca-11e5-89b1-e724eb27d021.png)

**Comment by kkrysiak** [comment]
Additional terms we would like to have added include:
`Her2-receptor positive breast cancer - DOID:0060079`
`Her2-receptor negative breast cancer - DOID:0060080`
`triple-receptor negative breast cancer - DOID:0060081`

@arpaddanos brought these to my attention.

**Comment by kkrysiak** [comment]
Since this is a repeat of https://github.com/genome/civic-server/issues/118, I'm going to close this here and add the above diseases to our other issue.
