### ISSUE TITLE
Evidence item attribution view and status do not agree

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#125]
For example, see the screenshot below.  Or several evidence items for PTEN LOSS:
https://civic.genome.wustl.edu/#/events/genes/41/summary/variants/214/summary#variant

Single example:
https://civic.genome.wustl.edu/#/events/genes/41/summary/variants/214/summary/evidence/714/summary#evidence

The view says that this item was accepted by @nspies13 6 days ago.  But the Accept/Reject buttons are still showing, and the status of this evidence item in the admin interface still says submitted (https://civic.genome.wustl.edu/admin/evidence_items/714).  

If I accept one of these again it seems to work and show me as the person who accepted it.

**Comment by acoffman** [comment]
Sorry, this was the temporary result of my event back-fill being a little overeager on its first pass. You shouldn't encounter this anymore now that it has completed its run!

**Comment by malachig** [comment]
Oh, I was hoping Nick really had reviewed and accepted all of these.  LOL.  :). Looks good now.  We'll keep working our way through these.  Thanks for the clarification!
