### ISSUE TITLE
Update glossary

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#126]
Time to review and update the glossary.  To do this update this file: `civic-server/text/glossary.yml`. Then to update the values in the database:

```
rake --tasks
rake civic:import_glossary
```

**Comment by acoffman** [comment]
As quick clarification `rake --tasks` just lists all the possible tasks out so you can find the one you want. If you just want to run `rake civic:import_glossary` there's no need to run `--tasks` first.

**Comment by malachig** [comment]
Right, just a reminder to myself for how to find these rake tasks. :)

**Comment by kkrysiak** [comment]
Thank you for documenting this, the short mention in the meeting wasn't enough for me to figure out how to do it.

**Comment by malachig** [comment]
I think we can resolve this now.  There is another issue to allow sub-headings.  KK has updated the glossary a bit.  And we now know how to update the glossary in a test instance.
