### ISSUE TITLE
Some diagnostic/prognostic evidence items have 'N/A' for drug, others are blank

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#127]
@acoffman and @jmcmichael I'm not sure if this is related to server, client or both.

I expect that all diagnostic and prognostic entries should show 'N/A' for the drug value.  All predictive evidence items should have a drug, and the field should only be blank for the subset of these where we were not able to enter a drug because it was not in the DB.  Once that is fixed we would fill in the blanks and not expect to ever see this field being blank... Is that reasonable?

Not sure how we want to actually implement this.  

1. Could just be a display thing where N/A is always shown for predictive/prognostic entries.  

2. Or we could backfill the database with 'N/A' values and when a new prognostic/diagnostic entry is created we could automatically enter 'N/A' in the DB.

**Comment by malachig** [comment]
I think we should do this but I am open to other suggestions:
1.) Drug name should never be the string 'N/A' in the database.  If there is no drug entry, it is just NULL
2.) In the front-end the data grid should always **display** 'N/A' for prognostic and diagnostic evidence items.

Thus the only place where we would have an empty field for drug is predictive evidence statements where the user did not enter one.  I find it really jarring to have these empty fields on so many evidence items.  It should only be empty when there is curation work needed to fix the missing data.  That way if curation is done, it is obvious, if it is truly not applicable this is obvious, and if a curator needs to do something, this is also obvious.

@jmcmichael and @acoffman this issue requires changes to both front and back end.  
- In the back end, the drug called 'N/A' should be removed.  That is not a valid drug entity.
- In the back end, all evidence items that link to drug 'N/A' for their drug should be reset to NULL
- In the front end, the evidence grid should display 'N/A' when evidence type is NOT predictive (i.e. when it is prognostic and diagnostic).

**Comment by malachig** [comment]
Marking this high priority as is goes along with other drug related cleanup that is happening right now.

**Comment by kkrysiak** [comment]
Would it make sense to just not display the field for prognostic and diagnostic evidence?

**Comment by malachig** [comment]
Maybe, but I think it is more clear to show that it is 'N/A'.  And we have no choice for the datagrid which will often contain a combination of evidence items of the three types.  

Don't really like the idea of cycling through evidence items and having the layout change based on evidence type.  If you leave the layout the same then you would just have an empty space which would maybe look weird.

**Comment by kkrysiak** [comment]
That makes sense. Let's stick with the N/A being displayed.

**Comment by jmcmichael** [comment]
Just committed an update to the summary and grid that will show 'N/A' if it get an empty array.

**Comment by acoffman** [comment]
I'll do the data fix with our next deploy and this should be complete!

**Comment by acoffman** [comment]
Complete and pushed. Waiting on puppet to deploy to prod.
