### ISSUE TITLE
Once rejected an new evidence item can not be recovered

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#128]
I accidentally hit the reject button on this evidence item:
https://civic.genome.wustl.edu/admin/evidence_items/749

Is it possible to create path at least in the admin interface to change the status back to pending or accepted?

**Comment by acoffman** [comment]
We should retain the status history in these cases.

**Comment by malachig** [comment]
To summarize, in the admin interface, admins should be able to manually change the status of an evidence item.

In the front end, if a revision is proposed for a rejected evidence item, the status of that evidence item will be returned to pending/submitted.  This can effectively be a mechanism for appeal of a rejected a evidence item.

**Comment by acoffman** [comment]
Admins are now presented with status change buttons in the admin interface. An accepted item can be rejected or "resubmitted" (maybe need a better name for that - basically just puts it back in "submitted" state) and a rejected item can be accepted or resubmitted.

If a revision is suggested to a rejected evidence item, it will now automatically change back to "pending".

**Comment by malachig** [comment]
When I accepted a revision on the evidence item again, it seemed to work but the status was still rejected. Refreshing page did not help.

Using the resubmit option in the admin interface did work though.

**Comment by acoffman** [comment]
In this case - proposing the revision is what will move the evidence item back to `Pending`, if the revision was pre-existing, accepting it won't change the status.

Both cases should probably trigger the status change though - that's an easy fix!

**Comment by malachig** [comment]
Ah, now I understand.  Yeah, I agree that both cases should trigger the change.

**Comment by acoffman** [comment]
Update pushed to master - both suggesting a change to a rejected evidence item and accepting a change to a rejected evidence item will cause the evidence item to go back into a `submitted` state!
