### ISSUE TITLE
Disease appears in drop down but has no DOID.

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-server#129]
This should bring up DOID:2513 but instead gives a null value.

<img width="489" alt="screen shot 2015-12-30 at 3 15 36 am" src="https://cloud.githubusercontent.com/assets/8527125/12048701/f5a13748-aea3-11e5-9e67-1b1720f39d4d.png">

**Comment by acoffman** [comment]
This is cleaned up and fixed! There's only one entry for Basal Cell Carcinoma now, the DOID is present, and the capitalization is standardized with the rest of our disease names.
