### ISSUE TITLE
Additional OAuth providers

### ISSUE THREAD

**Issue by acoffman** [genome/civic-server#13]
Google, ORCid?

**Comment by malachig** [comment]
I think we should start with these two.  Quite a few of the early testers that we hope to get feedback from do not have a github account...

**Comment by malachig** [comment]
LinkedIn and Twitter would be great also.

**Comment by acoffman** [comment]
So, for Google OAuth, we'll need to set up a new application for civic on the google developer site. I can set this up with my own personal Google account, but that doesn't seem ideal. From the Google Analytics ticket, it sounds like both @malachig and @obigriffith have admin on the TGI organization account. Can one of you set up an app on that account by following the instructions here: https://github.com/zquestz/omniauth-google-oauth2#omniauth-google-oauth2-strategy. I went through most of the flow on my own account and its pretty simple.

Once its set up, then if you can send me the client id and client secret and I can incorporate it into CIVIC.

**Comment by acoffman** [comment]
(I don't expect that we'll be able to ship this today anyways, but before AGBT would be awesome!)

**Comment by malachig** [comment]
I think we were given view access in Google Analytics for the DGIdb application.  I don't think we have admin on the TGI organization account though.  Maybe @mcallaway can clarify this?

**Comment by malachig** [comment]
Here is a working list of ideas for OAuth providers:
- [x] ORCid
- [x] Google
- [x] LinkedIn
- [x] ResearchGate
- [x] Twitter
- [x] Yahoo

**Comment by acoffman** [comment]
I've just pushed an update that allows for logging in with Google and ORCid. We'll need to update the frontend to support this and decide the flow for credential collisions (two people with the same usernames on different sites, etc).
