### ISSUE TITLE
Combine completion suggestions from our local database and PubChem for drug names

### ISSUE THREAD

**Issue by acoffman** [genome/civic-server#130]
Make sure we de-dup the suggestions (given precedence to local database entries in the process)

**Comment by malachig** [comment]
This seems conceptually related to #101 and #148 , general things need to help us clean up drug confusion...  :)

**Comment by acoffman** [comment]
The endpoint for this exists server side. I've opened genome/civic-client#345 to integrate it into the frontend and I'll try to tackle that next.
