### ISSUE TITLE
Why does the autocomplete for adding variants to a variant group omit some variants?

### ISSUE THREAD

**Issue by acoffman** [genome/civic-server#132]

**Comment by obigriffith** [comment]
A good example is for ERBB2. I was trying to add the "ERBB2 - OVEREXPRESSION" variant to the "HER2 Activating" variant group but it does not show in the type-ahead list when trying to add the variant. 

<img width="950" alt="screenshot 2015-12-30 18 26 50" src="https://cloud.githubusercontent.com/assets/1638042/12059549/f65a8278-af22-11e5-939f-e831dad73b69.png">

**Comment by acoffman** [comment]
We need to search gene name as well as variant, and prioritize results by gene name. We should also expand the number of suggestions beyond 5
