### ISSUE TITLE
Can't filter on Clinical Significance N/A in the advanced search grid

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-server#140]
N/A is not in the filter drop down.

<img width="1205" alt="screen shot 2016-01-06 at 6 58 40 pm" src="https://cloud.githubusercontent.com/assets/8527125/12159409/98b531d8-b4a7-11e5-88ef-290e3ef5c033.png">

**Comment by acoffman** [comment]
This is fixed in master and will go out in the next release!
