### ISSUE TITLE
Sorting and display of 'Browse by Gene' view.  Default sort not working?

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#149]
Right now on the live site if I go to the `Browse by Gene` view I see what appears to be an alphabetical list of genes.

But valid genes are missing.  For example `AR` and `AREG` do not appear.  If I go beyond the first page, to look for the missing genes the sort order appears fairly random.

If actively sort by hitting the header, it seems to show the correct sort order.

I'm guessing by default we are seeing genes in the order they were added to the database?

Perhaps the default behavior of the end point this table is hitting should be to return sorted by gene name?  Either that or in the front end we initialize this grid with a sorted state?

**Comment by acoffman** [comment]
Your hunch was right, it was just displaying in database order on initial load. Looks like the default value for the sort was sending the wrong param. I've fixed this in https://github.com/genome/civic-client/commit/73d85925cdca4b4da189fc38c151cd9fa2e71500.
