### ISSUE TITLE
Disease and drug names should be Title Case

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#15]
Looking at views in the CIVIC interface, the few spots where casing is not consistent are a bit jarring to the eye.  In particular, on import, or when we query and display options from an external API, can we convert disease names to Title Case?  Also can we similarly convert drug names to Title Case.

Note that in both of these cases there may be diseases that are like 'AML' or drug names that are like 'PLX4720'.  We don't want to lower case any of these letters.  

So what I really mean, is to make the first letter of each word upper case, and leave the rest of the word alone.

**Comment by acoffman** [comment]
Done, and and a new data dump pushed to master.
