### ISSUE TITLE
create a "last reviewed by" tag for life cycle

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-server#150]
Right now an evidence item shows (1) "submitted by" - who originally submitted the evidence statement; (2) "accepted by" - who accepted the original submission; (3) "Last modified by" - who last revised the statement (once accepted). One thing that feels missing is the last person who reviewed or modified a revision. In some ways it is as much work to review and approve a revision as it is to propose a revision but this effort isn't recognized by a life cycle tag.

**Comment by acoffman** [comment]
That makes sense to me. Generally this would be person who approved the change that was generated by the "Last modified by" user correct? That shouldn't be difficult to add!

**Comment by obigriffith** [comment]
Yes. That's correct.

**Comment by acoffman** [comment]
This is complete and will go out in the next deploy!
