### ISSUE TITLE
Attempting to delete an evidence item in the admin interface fails

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#151]
I am trying to delete two redundant evidence items: EID49 and EID188.

When I try to do this in the admin interface I get an unknown error:

![screen shot 2016-02-09 at 10 42 51 am](https://cloud.githubusercontent.com/assets/856728/12923078/e2d63546-cf19-11e5-8e32-b6a698d01987.png)

**Comment by malachig** [comment]
Note, we are actually not sure if we want to delete these two evidence items.  Though the bug report still stands as we will want to delete some evidence item at some point I'm sure.

**Comment by malachig** [comment]
Actually we still want to delete EID49.

**Comment by malachig** [comment]
Also would like to delete this evidence item:
https://civic.genome.wustl.edu/admin/evidence_items/900

Getting an error.

**Comment by acoffman** [comment]
Complete and pushed. Waiting on puppet to deploy to prod.
