### ISSUE TITLE
[ERROR -DB Import] Error in relation "genes" does not exist.

### ISSUE THREAD

**Issue by christopherwelsh** [genome/civic-server#156]
Hi, I get a rake aborted error. Assistance welcome. I think I am almost there :-) 

rake db:drop
rake db:create
And then:
rake civic:import['import/GeneSummaries.txt','import/VariantSummaries.txt','import/ClinActionEvidence.txt','import/VariantGroupSummaries.txt']

Here are my databases and I believe they have tables.
i.e. from psql
civic_development=# \l
        
List of databases
       Name        |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges   
-------------------+----------+----------+-------------+-------------+-----------------------
 civic_development | postgres | UTF8     | en_AU.UTF-8 | en_AU.UTF-8 | 
 civic_test        | bioinf   | UTF8     | en_AU.UTF-8 | en_AU.UTF-8 | 
 postgres          | postgres | UTF8     | en_AU.UTF-8 | en_AU.UTF-8 | 
 template0         | postgres | UTF8     | en_AU.UTF-8 | en_AU.UTF-8 | =c/postgres          +
                   |          |          |             |             | postgres=CTc/postgres
 template1         | postgres | UTF8     | en_AU.UTF-8 | en_AU.UTF-8 | =c/postgres          +
                   |          |          |             |             | postgres=CTc/postgres
(5 rows)

My database config file:
less database.yml 

default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  host: localhost

development:
  <<: *default
  database: civic_development
  host: localhost
  username: postgres

test:
  <<: *default
  database: civic_test
  <% if ENV['TRAVIS_BUILD'] %>
  username: postgres
  host: localhost
  <% end %>

production:
  <<: *default
  database: civic

Error output as follows:

[bioinf@localhost civic-server]$ rake civic:import['import/GeneSummaries.txt','import/VariantSummaries.txt','import/ClinActionEvidence.txt','import/VariantGroupSummaries.txt']
rake aborted!
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "genes" does not exist
LINE 5:                WHERE a.attrelid = '"genes"'::regclass
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"genes"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
/home/bioinf/.gem/gems/rack-mini-profiler-0.9.6/lib/patches/db/pg.rb:90:in `exec'
/home/bioinf/.gem/gems/rack-mini-profiler-0.9.6/lib/patches/db/pg.rb:90:in `async_exec'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
/home/bioinf/.gem/gems/activesupport-4.2.5.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `exec_no_cache'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/postgresql_adapter.rb:584:in `execute_and_clear'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/postgresql_adapter.rb:733:in `column_definitions'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:186:in `columns'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/attributes.rb:93:in `columns'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/attributes.rb:98:in `columns_hash'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/relation/query_methods.rb:969:in `block in create_binds'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/relation/query_methods.rb:967:in `each'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/relation/query_methods.rb:967:in `partition'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/relation/query_methods.rb:967:in `create_binds'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/relation/query_methods.rb:954:in `build_where'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/relation/query_methods.rb:584:in `where!'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/relation/query_methods.rb:574:in `where'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/querying.rb:10:in `where'
/home/bioinf/civic-server/app/models/concerns/soft_deletable.rb:4:in `block (2 levels) in <module:SoftDeletable>'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/default.rb:105:in `call'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/default.rb:105:in `block (3 levels) in build_default_scope'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/relation.rb:302:in `scoping'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/default.rb:105:in `block (2 levels) in build_default_scope'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/default.rb:104:in `each'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/default.rb:104:in `inject'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/default.rb:104:in `block in build_default_scope'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/default.rb:127:in `evaluate_default_scope'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/default.rb:103:in `build_default_scope'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/named.rb:33:in `default_scoped'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/named.rb:28:in `all'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/querying.rb:10:in `where'
/home/bioinf/civic-server/lib/importer/entity_maps/base.rb:43:in `block in get_entity_from_row'
/home/bioinf/civic-server/lib/importer/entity_maps/base.rb:41:in `map'
/home/bioinf/civic-server/lib/importer/entity_maps/base.rb:41:in `get_entity_from_row'
/home/bioinf/civic-server/lib/importer/gene_summaries_adaptor.rb:8:in `create_entities_for_row'
/home/bioinf/civic-server/lib/importer/tsv_reader.rb:16:in `block (2 levels) in import!'
/home/bioinf/civic-server/lib/importer/tsv_reader.rb:14:in `block in import!'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/transactions.rb:220:in `transaction'
/home/bioinf/civic-server/lib/importer/tsv_reader.rb:13:in `import!'
/home/bioinf/civic-server/lib/tasks/import.rake:29:in `block (3 levels) in <top (required)>'
/home/bioinf/civic-server/lib/tasks/import.rake:26:in `each'
/home/bioinf/civic-server/lib/tasks/import.rake:26:in `block (2 levels) in <top (required)>'
PG::UndefinedTable: ERROR:  relation "genes" does not exist
LINE 5:                WHERE a.attrelid = '"genes"'::regclass
                                          ^
/home/bioinf/.gem/gems/rack-mini-profiler-0.9.6/lib/patches/db/pg.rb:90:in `exec'
/home/bioinf/.gem/gems/rack-mini-profiler-0.9.6/lib/patches/db/pg.rb:90:in `async_exec'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
/home/bioinf/.gem/gems/activesupport-4.2.5.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `exec_no_cache'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/postgresql_adapter.rb:584:in `execute_and_clear'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/postgresql_adapter.rb:733:in `column_definitions'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:186:in `columns'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/attributes.rb:93:in `columns'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/attributes.rb:98:in `columns_hash'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/relation/query_methods.rb:969:in `block in create_binds'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/relation/query_methods.rb:967:in `each'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/relation/query_methods.rb:967:in `partition'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/relation/query_methods.rb:967:in `create_binds'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/relation/query_methods.rb:954:in `build_where'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/relation/query_methods.rb:584:in `where!'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/relation/query_methods.rb:574:in `where'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/querying.rb:10:in `where'
/home/bioinf/civic-server/app/models/concerns/soft_deletable.rb:4:in `block (2 levels) in <module:SoftDeletable>'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/default.rb:105:in `call'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/default.rb:105:in `block (3 levels) in build_default_scope'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/relation.rb:302:in `scoping'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/default.rb:105:in `block (2 levels) in build_default_scope'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/default.rb:104:in `each'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/default.rb:104:in `inject'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/default.rb:104:in `block in build_default_scope'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/default.rb:127:in `evaluate_default_scope'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/default.rb:103:in `build_default_scope'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/named.rb:33:in `default_scoped'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/named.rb:28:in `all'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/querying.rb:10:in `where'
/home/bioinf/civic-server/lib/importer/entity_maps/base.rb:43:in `block in get_entity_from_row'
/home/bioinf/civic-server/lib/importer/entity_maps/base.rb:41:in `map'
/home/bioinf/civic-server/lib/importer/entity_maps/base.rb:41:in `get_entity_from_row'
/home/bioinf/civic-server/lib/importer/gene_summaries_adaptor.rb:8:in `create_entities_for_row'
/home/bioinf/civic-server/lib/importer/tsv_reader.rb:16:in `block (2 levels) in import!'
/home/bioinf/civic-server/lib/importer/tsv_reader.rb:14:in `block in import!'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/transactions.rb:220:in `transaction'
/home/bioinf/civic-server/lib/importer/tsv_reader.rb:13:in `import!'
/home/bioinf/civic-server/lib/tasks/import.rake:29:in `block (3 levels) in <top (required)>'
/home/bioinf/civic-server/lib/tasks/import.rake:26:in `each'
/home/bioinf/civic-server/lib/tasks/import.rake:26:in `block (2 levels) in <top (required)>'
Tasks: TOP => civic:import
(See full trace by running task with --trace)
[bioinf@localhost civic-server]$ rake civic:import['import/GeneSummaries.txt','import/VariantSummaries.txt','import/ClinActionEvidence.txt','import/VariantGroupSummaries.txt'] 

rake aborted!
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "genes" does not exist
LINE 5:                WHERE a.attrelid = '"genes"'::regclass
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"genes"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
/home/bioinf/.gem/gems/rack-mini-profiler-0.9.6/lib/patches/db/pg.rb:90:in `exec'
/home/bioinf/.gem/gems/rack-mini-profiler-0.9.6/lib/patches/db/pg.rb:90:in `async_exec'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
/home/bioinf/.gem/gems/activesupport-4.2.5.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `exec_no_cache'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/postgresql_adapter.rb:584:in `execute_and_clear'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/postgresql_adapter.rb:733:in `column_definitions'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:186:in `columns'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/attributes.rb:93:in `columns'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/attributes.rb:98:in `columns_hash'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/relation/query_methods.rb:969:in `block in create_binds'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/relation/query_methods.rb:967:in `each'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/relation/query_methods.rb:967:in `partition'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/relation/query_methods.rb:967:in `create_binds'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/relation/query_methods.rb:954:in `build_where'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/relation/query_methods.rb:584:in `where!'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/relation/query_methods.rb:574:in `where'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/querying.rb:10:in `where'
/home/bioinf/civic-server/app/models/concerns/soft_deletable.rb:4:in `block (2 levels) in <module:SoftDeletable>'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/default.rb:105:in `call'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/default.rb:105:in `block (3 levels) in build_default_scope'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/relation.rb:302:in `scoping'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/default.rb:105:in `block (2 levels) in build_default_scope'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/default.rb:104:in `each'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/default.rb:104:in `inject'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/default.rb:104:in `block in build_default_scope'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/default.rb:127:in `evaluate_default_scope'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/default.rb:103:in `build_default_scope'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/named.rb:33:in `default_scoped'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/named.rb:28:in `all'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/querying.rb:10:in `where'
/home/bioinf/civic-server/lib/importer/entity_maps/base.rb:43:in `block in get_entity_from_row'
/home/bioinf/civic-server/lib/importer/entity_maps/base.rb:41:in `map'
/home/bioinf/civic-server/lib/importer/entity_maps/base.rb:41:in `get_entity_from_row'
/home/bioinf/civic-server/lib/importer/gene_summaries_adaptor.rb:8:in `create_entities_for_row'
/home/bioinf/civic-server/lib/importer/tsv_reader.rb:16:in `block (2 levels) in import!'
/home/bioinf/civic-server/lib/importer/tsv_reader.rb:14:in `block in import!'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/transactions.rb:220:in `transaction'
/home/bioinf/civic-server/lib/importer/tsv_reader.rb:13:in `import!'
/home/bioinf/civic-server/lib/tasks/import.rake:29:in `block (3 levels) in <top (required)>'
/home/bioinf/civic-server/lib/tasks/import.rake:26:in `each'
/home/bioinf/civic-server/lib/tasks/import.rake:26:in `block (2 levels) in <top (required)>'
PG::UndefinedTable: ERROR:  relation "genes" does not exist
LINE 5:                WHERE a.attrelid = '"genes"'::regclass
                                          ^
/home/bioinf/.gem/gems/rack-mini-profiler-0.9.6/lib/patches/db/pg.rb:90:in `exec'
/home/bioinf/.gem/gems/rack-mini-profiler-0.9.6/lib/patches/db/pg.rb:90:in `async_exec'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
/home/bioinf/.gem/gems/activesupport-4.2.5.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `exec_no_cache'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/postgresql_adapter.rb:584:in `execute_and_clear'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/postgresql_adapter.rb:733:in `column_definitions'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:186:in `columns'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/attributes.rb:93:in `columns'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/attributes.rb:98:in `columns_hash'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/relation/query_methods.rb:969:in `block in create_binds'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/relation/query_methods.rb:967:in `each'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/relation/query_methods.rb:967:in `partition'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/relation/query_methods.rb:967:in `create_binds'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/relation/query_methods.rb:954:in `build_where'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/relation/query_methods.rb:584:in `where!'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/relation/query_methods.rb:574:in `where'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/querying.rb:10:in `where'
/home/bioinf/civic-server/app/models/concerns/soft_deletable.rb:4:in `block (2 levels) in <module:SoftDeletable>'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/default.rb:105:in `call'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/default.rb:105:in `block (3 levels) in build_default_scope'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/relation.rb:302:in `scoping'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/default.rb:105:in `block (2 levels) in build_default_scope'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/default.rb:104:in `each'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/default.rb:104:in `inject'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/default.rb:104:in `block in build_default_scope'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/default.rb:127:in `evaluate_default_scope'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/default.rb:103:in `build_default_scope'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/named.rb:33:in `default_scoped'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/scoping/named.rb:28:in `all'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/querying.rb:10:in `where'
/home/bioinf/civic-server/lib/importer/entity_maps/base.rb:43:in `block in get_entity_from_row'
/home/bioinf/civic-server/lib/importer/entity_maps/base.rb:41:in `map'
/home/bioinf/civic-server/lib/importer/entity_maps/base.rb:41:in `get_entity_from_row'
/home/bioinf/civic-server/lib/importer/gene_summaries_adaptor.rb:8:in `create_entities_for_row'
/home/bioinf/civic-server/lib/importer/tsv_reader.rb:16:in `block (2 levels) in import!'
/home/bioinf/civic-server/lib/importer/tsv_reader.rb:14:in `block in import!'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/home/bioinf/.gem/gems/activerecord-4.2.5.1/lib/active_record/transactions.rb:220:in `transaction'
/home/bioinf/civic-server/lib/importer/tsv_reader.rb:13:in `import!'
/home/bioinf/civic-server/lib/tasks/import.rake:29:in `block (3 levels) in <top (required)>'
/home/bioinf/civic-server/lib/tasks/import.rake:26:in `each'
/home/bioinf/civic-server/lib/tasks/import.rake:26:in `block (2 levels) in <top (required)>'
Tasks: TOP => civic:import
(See full trace by running task with --trace)

Regards,

Chris

**Comment by obigriffith** [comment]
Looks like you are missing "rake db:schema:load". I just recently installed on my laptop and this worked for me:

```
rake db:drop
rake db:create
rake db:schema:load
rake civic:load
```

**Comment by christopherwelsh** [comment]
Hi Obi,

Now for a Slap plan of the hand on  the forehead moment.

 :-)

Regards,

Christopher Welsh
Systems Administrator, Research Support Services
Cancer Research Division
Peter MacCallum Cancer Centre
http://www.petermac.org<http://www.petermac.org/>

Phone +61 3 9656 1512
Fax +61 3 9656 1411
E-mail Christopher.Welsh@petemac.org




[unknown.png]

[unknown_1.png]

**Comment by acoffman** [comment]
It sounds like this is resolved for now, but feel free to open more issues as you run into them. The README directions are really more geared towards someone who wants to set up a development environment. We should prepare documentation for a production deployment to make this easier going forward!

**Comment by christopherwelsh** [comment]
Hi Thanks for all the great help. Still a couple of issues.

1. Proxy - We are behind a proxy where we need to auth in order to connect out.
I have discovered civic-server fails when it is trying to connect to mygene.info PORT 80 to retrieve some information. Can you please tell me if there is something like a  HTTP_PROXY variable required to be set or something like that in the config?

2. OAuth has now been registered but I get page not found. I will leave that until I sort the proxy issue first.

Thanks
