### ISSUE TITLE
sort variant and gene browse by number of evidence items

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#157]
Until #141 is implemented we should by default sort both browse views by evidence item count.  Descending.

This is important because right now a new user who is a clinician will arrive at CIViC and start to browse existing gene/variant entries.  What they will see is a list of genes/variants that feels quite random, many with very little support, and some that are not widely accepted as clinically relevant at all, and even in some cases, barely accepted as relevant to cancer even...

On the other hand, when I sort by evidence count, the list is really beautiful.

@acoffman is this as straightforward as changing the default return for the endpoint that populates each of these two browse data grids?

**Comment by acoffman** [comment]
This should be pretty straightforward. Evidence Item count is already a field available for sorting, so we just need to make it the default sort in the grid component on the frontend. If that doesn't work out, I can make it sort by the count when no other sort params are provided (though that might be a little confusing).

**Comment by malachig** [comment]
Ah okay, so this is a front end thing. @jmcmichael can we adjust these grids to sort on evidence item count by default?
