### ISSUE TITLE
after acceptance an evidence item disappeared from the evidence item grid

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#158]
In the live site:

Obi approved this evidence item.  And I can see it if I go straight to the link, but otherwise it has disappeared for me.
https://civic.genome.wustl.edu/#/events/genes/20/summary/variants/306/summary/evidence/1012/summary

Does not show in the variant view and I can not retrieve it by advanced search.  But I see it in the admin interface and if I follow that link...

I wonder if other things exist but can't be seen.  I thought it might be a browser caching problem because it was also looking at it when Obi approved it, but I get the same thing in Firefox and Safari.

The only unusual thing about it, is the length of the evidence statement. @jmcmichael could that cause a problem for display in the data grid code maybe?

**Comment by malachig** [comment]
Actually length does not make sense because it was displaying in the grid before it was approved just fine.  I tried to revise it and approve the revision.  That worked but it still will not display in the grid for me.

**Comment by obigriffith** [comment]
I moved it in the admin interface from Amplification to over-expression since the publication refers to HER2 overexpression which may or may not be the result of amplification. Are you perhaps still looking for it in the Amplification page?

**Comment by obigriffith** [comment]
Of course, now looking in the methods I see that they actually say patients were selected based on "HER2-overexpressing (based on immunohistochemistry 3+ or 2+, and positive reflex fluorescence in situ hybridisation)".  If they really mean that AND positive FISH then they are all probably amplification cases in addition to overexpression cases. I kind of hate that we have both and if only one could be chosen I would put everything under overexpression. I also wish there was a way to revise the variant rather than going to the admin interface where this change is then untracked.

**Comment by malachig** [comment]
Ah!  Sneaky, sneaky.  Sorry, should have made that connection.  I'll close this issue.  Yes, most of these studies refer to amplification (via FISH, CGH, etc.) and expression/overexpression (via IHC, ELISA, rtPCR) interchangeably.   Several studies assess both, or use a combination of assays to define HER2 status.  I agree, we should probably not have both.  I was also thinking we should just put them all under `overexpression` or even just `expression`.  And once we have variant synonyms we can define that we mean either or in this case.

**Comment by obigriffith** [comment]
Yeah. That makes sense. Another option is to put them both in variant group HER2 activating but for some reason I can't get that to work. Also, surprised that you can't edit variant name for an evidence statement. Are both of those separate existing issues?

**Comment by malachig** [comment]
Bot sure I follow.  I have changed variant names recently...  But the name is only a name and is associated with a variant record which is totally independent of evidence item records.  You will have to move evidence items in the admin interface to the variant you want.

**Comment by obigriffith** [comment]
Why not allow you to edit the associated variant for an evidence item?  Effectively moving that evidence item from one variant to another? Basically have the admin interface functionality in the main interface. If you only allowed within-gene moves this could be as simple as a drop down for all the existing variants for that evidence item. Or, maybe you decide that it should really be under a new gene/variant. In the add evidence page there are both gene/variant fields so it seems like it should be possible to have them on the edit evidence page?

**Comment by malachig** [comment]
Oh I see, you meant in the front-end interface instead of admin.  Yeah, had that thought too.  Maybe its not too hard.  I also can't get variant groups additions to work.  Can't get the variants I want to appear in the type ahead so I can't add them.

**Comment by kkrysiak** [comment]
The search issue has already been documented here: 
https://github.com/genome/civic-server/issues/132

Maybe we should open a separate issue to address allowing the name change in the main interface.
