### ISSUE TITLE
civic import fails on error

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-server#16]
I followed the install instructions but did both the rake civic:load and then the rake civic:import. The import failed on the error below. Is this because that import method is currently broken?  Or can you not import directly from the files after you have already loaded from the existing database dump?

Obis-MacBook-Air:civic-server ogriffit$ rake civic:import['import/GeneSummaries.txt','import/VariantSummaries.txt','import/ClinActionEvidence.txt', 'import/VariantGroupSummaries.txt']
rake aborted!
Don't know how to build task 'civic:import[import/GeneSummaries.txt,import/VariantSummaries.txt,import/ClinActionEvidence.txt,'

**Comment by jmcmichael** [comment]
For what it's worth, I just did a successful pull and drop/create/migrate etc. with the following commands:
```bash
rake db:drop
rake db:create
rake db:schema:load
rake db:migrate
rake civic:load

**Comment by obigriffith** [comment]
Yeah. That worked for me too. Just the old import method didn't.

**Comment by acoffman** [comment]
As stupid as it is, rake (like make) is whitespace sensitive. Its the extra space after the comma preceding the variant group summaries file that's breaking things. I've pushed an update to the readme that removes the space for easy of copy/paste!
