### ISSUE TITLE
Drug merge only works sometimes

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-server#163]
I started trying to clean up redundant drugs using the new merge drugs utility in admin interface. For example I started merging drugs with multiple entries having the identical name (e.g., Carboplatin and Cetuximab both have multiple entries).  I succeeded in merging Cetuximab (16) with Cetuximab (NN) several times but then started hitting cases that error out. 

For example, trying to merge Cetuximab (16) with Cetuximab (197) gives the "We're sorry, but something went wrong. If you are the application owner check the logs for more information."

**Comment by acoffman** [comment]
Fixed in master and will go out in the next release!
