### ISSUE TITLE
[Fail] mygene.info port 80 where do I set the proxy variable to redirect this through a proxy?

### ISSUE THREAD

**Issue by christopherwelsh** [genome/civic-server#165]
Hi Thanks for all the great help. Still a couple of issues.

Proxy - We are behind a proxy where we need to auth in order for mygene.info to connect out.
I have discovered civic-server fails to return results when it is trying to connect to mygene.info PORT 80 to retrieve some information. Can you please tell me if there is something like a HTTP_PROXY variable required to be set or something like that in the config?

OAuth has now been registered but I get page not found. I will leave that until I sort the proxy issue first.

Thanks

**Comment by obigriffith** [comment]
I don't think our version of civic-server is behind a proxy so you might be in uncharted waters. I could be wrong though. @acoffman do you have any advice on what might fix this?

**Comment by christopherwelsh** [comment]
That could be the case. I think the HTTP module you use with mygene.info may not be proxy aware/configurable? I’m no programmer so I would welcome feedback and workaround advice. :-)

Regards,

Christopher Welsh
Systems Administrator, Research Support Services
Cancer Research Division
Peter MacCallum Cancer Centre
http://www.petermac.org<http://www.petermac.org/>

Phone +61 3 9656 1512
Fax +61 3 9656 1411
E-mail Christopher.Welsh@petemac.org




[unknown.png]

[unknown_1.png]

**Comment by obigriffith** [comment]
Someone else who might be able to help is @newgene (Chunlei Wu) who leads the mygene.info and myvariant.info projects and helped us integrate mygene.info into CIViC.

**Comment by christopherwelsh** [comment]
Thx.

**Comment by acoffman** [comment]
Hi @christopherwelsh, we are just using the HTTP client in the Ruby standard library. A proxy can be set via environment variable and all connections will automatically be routed though it. The environment variable in question is `http_proxy` and can be set in your shell environment like any other environment variable. If you would prefer to set it in code, you can add a new `.rb` file in `config/initializers/your_file.rb` and then set `ENV['http_proxy'] = 'http://your.proxy.ip:port'`. Let me know if that works for you!

Thanks,
Adam

**Comment by christopherwelsh** [comment]
Hi Adam,

From memory I had that set on the server by default as other apps on the server use ‘http_proxy’ and work fine. I will double check when I get in in an 90 minutes.

Regards,

Christopher Welsh
Systems Administrator, Research Support Services
Cancer Research Division
Peter MacCallum Cancer Centre
http://www.petermac.org<http://www.petermac.org/>

Phone +61 3 9656 1512
Fax +61 3 9656 1411
E-mail Christopher.Welsh@petemac.org




[unknown.png]

[unknown_1.png]

**Comment by christopherwelsh** [comment]
Hi no luck. Here is the output when I select a variant under browse variant.


Started GET "/api/genes/4/mygene_info_proxy" for 172.deleted.deleted.deleted at 2016-02-23 09:04:28 +1100

Processing by GenesController#mygene_info_proxy as JSON

  Parameters: {"gene_id"=>"4"}

  User Load (0.7ms)  SELECT  "users".* FROM "users" WHERE "users"."deleted" = $1 AND "users"."id" IS NULL LIMIT 1  [["deleted", "f"]]

  Gene Load (0.8ms)  SELECT  "genes".* FROM "genes" WHERE "genes"."deleted" = $1 AND "genes"."id" = $2 LIMIT 1  [["deleted", "f"], ["id", 4]]

Completed 500 Internal Server Error in 180ms (ActiveRecord: 1.5ms)


Errno::ECONNREFUSED (Connection refused - connect(2) for "mygene.info" port 80):

  lib/scrapers/util.rb:5:in `make_get_request'

  app/models/my_gene_info.rb:15:in `make_request'

  app/models/my_gene_info.rb:4:in `block in get_by_gene_id'

  app/models/my_gene_info.rb:3:in `get_by_gene_id'

  app/controllers/genes_controller.rb:62:in `mygene_info_proxy'

  app/middleware/cross_origin_request.rb:7:in `call'




Here is proxy config: /home/bioinf/civic-server/config/initializers


ENV['http_proxy'] = 'http://my.proxy.server.addr:3128'

myproxy.rb (END)

I will shift over to my other VM and try this out.

Regards,

Christopher Welsh
Systems Administrator, Research Support Services
Cancer Research Division
Peter MacCallum Cancer Centre
http://www.petermac.org<http://www.petermac.org/>

Phone +61 3 9656 1512
Fax +61 3 9656 1411
E-mail Christopher.Welsh@petemac.org




[unknown.png]

[unknown_1.png]

**Comment by christopherwelsh** [comment]
Also getting this:


Started GET "/api/genes/4/mygene_info_proxy" for 127.0.0.1 at 2016-02-23 11:06:10 +1100
Processing by GenesController#mygene_info_proxy as JSON
  Parameters: {"gene_id"=>"4"}
  User Load (5.5ms)  SELECT  "users".* FROM "users" WHERE "users"."deleted" = $1 AND "users"."id" IS NULL LIMIT 1  [["deleted", "f"]]
  Gene Load (7.9ms)  SELECT  "genes".* FROM "genes" WHERE "genes"."deleted" = $1 AND "genes"."id" = $2 LIMIT 1  [["deleted", "f"], ["id", 4]]
Completed 500 Internal Server Error in 52ms (ActiveRecord: 13.4ms)

EOFError - end of file reached:
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/protocol.rb:153:in `rbuf_fill'
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/protocol.rb:134:in `readuntil'
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/protocol.rb:144:in `readline'


Regards,

Christopher Welsh
Systems Administrator, Research Support Services
Cancer Research Division
Peter MacCallum Cancer Centre
http://www.petermac.org<http://www.petermac.org/>

Phone +61 3 9656 1512
Fax +61 3 9656 1411
E-mail Christopher.Welsh@petemac.org




[unknown.png]

[unknown_1.png]

**Comment by christopherwelsh** [comment]
Ok, Here is the update. :-P

"strace" reveals my proxy.rb file containing the proxy setting is being opened when Civic-Server is being started. Civic-server is still ignoring the proxy directive in the file. 
ENV['http_proxy'] = 'http://127.0.0.1:3128'

tcpdump -i ens32 dst host mygene.info reveals that civic is still ignoring the proxy settings and attempting to go to mygene.info via port 80. 

I have an embarrassing workaround in place for now and would still welcome a solution.

The fix involves adding mygene.info to the /etc/hosts: local hosts line and setting the proxy to listen to port 80 on localhost. lol. 


I'm doing something really silly but cannot figure out what it is. 


Chris

**Comment by acoffman** [comment]
Closing as stale, but if you're still having this issue, please feel free to reopen!
