### ISSUE TITLE
Record and indicate evidence items sources that are open access vs. closed

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#166]
It would be great to eventually known which sources are actually publicly available as these have greater potential for transparent review by a broad community (not just those that pay for an expensive subscription).  On principle we should encourage (but not strictly require) contributions from open access sources.

**Comment by acoffman** [comment]
Do you imagine this would simply take the form of a boolean flag on the Source entity? Or is something more sophisticated needed to capture this information? Are there "degrees" of openness that we might need to record?

**Comment by malachig** [comment]
There are arguably degrees of openness perhaps.  But for our purposes, I think if a user on essentially any personal or public WIFI network can obtain a PDF of the full article without logging in or paying, then it is "open".  In other words they do not need to be in a library or at a university where a subscription is being paid. Anything short of this is "closed" access.

We may be able to mine this status directly/automatically from PubMed for the subset of articles that are in PubMed Central.  The remainder may not be so obvious and in some cases may change over time.

**Comment by kkrysiak** [comment]
Using PubMed Central, this may be as simple as If PMCID, display an "open access" icon?

**Comment by acoffman** [comment]
We're grabbing the PMCID where it exists and storing it, but we still should indicate this status (and probably link out) on the new "publication view."
