### ISSUE TITLE
Set up Google Analytics for CIViC so that we can gather usage statistics

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#17]
Not sure if this is done yet, but it would be great to have use tracking in place prior to the soft launch so that we can get a sense of how many people we are able to reach.

**Comment by acoffman** [comment]
Do you have a desired google account to use with this? If you want to email me the snippet your account generates, I can add it in! I assume we don't want to use my personal account :)

**Comment by obigriffith** [comment]
How was this done for DGI?  My recollection was that a shared/general account was set up and then shared with others. Malachi and I can both follow DGI analytics but to my knowledge it was not set up with either of our person gmails. Maybe Callaway remembers how this was done?

**Comment by acoffman** [comment]
Did some digging. So, from an email from @mcallaway around the time of DGIdb launch:

````
With Scott alongside me, I have updated dgi-db's git repo to:

- Use the TGI Google Analytics account number.
- Enable robots.txt

In addition, I have added Obi and Malachi to the admin list of the TGI Google Analytics Profile.  Obi, Malachi, you should receive email about this.
````

So it sounds like you guys have admin on the TGI Google analytics profil, so I I think you should be able to get the needed snippets from there?

**Comment by malachig** [comment]
I just logged in and found them (I think). 

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-35524735-1', 'auto');
  ga('send', 'pageview');

</script>
```

**Comment by obigriffith** [comment]
Is this snippet somehow tied to DGIdb though?  Don't recall how that 
actually works.


On 2/20/15 11:33 AM, Malachi Griffith wrote:
>
> I just logged in and found them (I think).
>
> |<script>
>    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
>    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
>    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
>    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
>
>    ga('create', 'UA-35524735-1', 'auto');
>    ga('send', 'pageview');
>
> </script>
> |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/genome/civic-server/issues/17#issuecomment-75283336>.
>

-- 
Obi L. Griffith, PhD
Assistant Professor of Medicine, Division of Oncology
Assistant Director, The Genome Institute
Washington University School of Medicine
Campus Box 8501, Room 5140
4444 Forest Park Ave
St. Louis, MO, 63108
Phone: 314-747-9248
www.obigriffith.org



____
This email message is a private communication. The information transmitted, including attachments, is intended only for the person or entity to which it is addressed and may contain confidential, privileged, and/or proprietary material. Any review, duplication, retransmission, distribution, or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is unauthorized by the sender and is prohibited. If you have received this message in error, please contact the sender immediately by return email and delete the original message from all computer systems. Thank you.

**Comment by malachig** [comment]
Hmmm, you might be right.  We might need to create a new account in Analytics using the TGI analytics login, generate a new unique snippet and then authorize people to access the report from there.  I think again @mcallaway or someone he referred us to was necessary to get this set up for DGIdb.

**Comment by acoffman** [comment]
Done!
