### ISSUE TITLE
variant summaries download should include coordinates etc

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-server#170]
Now, that rep transcript, coordinates, etc are fairly complete we should add these to the variant summaries data dumps.

**Comment by malachig** [comment]
Also we should add variant origin.  Right now we are coordinating with some folks at UCSC (@maximilianh and @haussler) who would like to integrate CIViC into the UCSC genome browser.  They are using these files so I'm marking this one high priority.

**Comment by malachig** [comment]
I also think that we should add the CIViC Gene, Variant and Evidence IDs where appropriate in these dumps.  This allows someone to relate the dump entries back to the live site (and would allow URLs to be constructed as well).

**Comment by maximilianh** [comment]
Yes, currently I don't have backlinks because of this.

**Comment by acoffman** [comment]
Fixed in master and will go out in the next release!

**Comment by obigriffith** [comment]
@maximilianh and @haussler. This went live today. For future you should have everything you need in the monthly data dumps (as of April 2016) for import into UCSC browser.
