### ISSUE TITLE
We should consider querying the myvariant.info API to get useful info like rsID or COSMIC frequency etc.

### ISSUE THREAD

**Issue by bainscou** [genome/civic-server#171]

**Comment by gspies** [comment]
Retrieving the rsID and cosmic frequency is easy using these 2 queries:

Get all variants
http://myvariant.info/v1/query/?q=_exists_:dbsnp%20AND%20_exists_:cosmic&fields=cosmic.mut_freq,dbsnp.rsid

Search by variant’s HGVS id
http://myvariant.info/v1/variant/chrX:g.142605160A%3EG?fields=cosmic.mut_freq,dbsnp.rsid

All we need to do is convert our variants into an HGVS id, and use that in the query.

**Comment by malachig** [comment]
@gspies having HGVS representations would in itself be quite valuable. :)

**Comment by acoffman** [comment]
#243 will address this/encapsulates this.
