### ISSUE TITLE
approving a suggested revision at variant level doesn't generate notification

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-server#177]
It seems that approving a suggested revision to a variant DOES NOT generate a notification for the suggester. Commenting on a suggested revision to a variant DOES generate a notification for the suggester. So, it seems like they are successfully subscribed to the variant but not getting notifications about approved (rejected?) revisions. Approving a suggested revision for an evidence item DOES generate a notification for the suggester. Mentions also working to generate notifications.

**Comment by acoffman** [comment]
Thanks, that's super helpful!

**Comment by jmcmichael** [comment]
Also, new suggested revisions to Genes do not appear to generate notifications.

**Comment by obigriffith** [comment]
For example, I proposed a revision to the Gene Summary for NPM1. Malachi had previously made modifications to that gene so we expected him to get a notification but he did not.
