### ISSUE TITLE
Import somatic/germline status from spreadsheets

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-server#19]
Germline vs somatic status exists in spreadsheet but is not currently being imported into database.

**Comment by nspies13** [comment]
Hey Adam, I have added variant_origin EntityMap, updated the app/models/variant_origin.rb file, and updated the clin_action_evidence_adaptor file. I have not touched the schema.rb file because I have little faith that I can figure it out. But hopefully these help.

**Comment by acoffman** [comment]
Hi @nspies13, I'm taking a look at your changes. Is it your intent that a variant could have multiple origins? Is this a piece of information stored at the evidence item level? That appears to be the case - is that correct? This opens the door to conflicting "variant origins" for a single variant. Is that acceptable?

**Comment by nspies13** [comment]
Yes, a variant has_many origins, but an evidence item should have only one. 

Nick

**Comment by acoffman** [comment]
Cool, just wanted to be sure. Thanks!

**Comment by acoffman** [comment]
Alright, its now being slurped in on import, and passed along in all evidence item api requests. Thanks for the assist Nick, you had it like 90% of the way there already! Just needed to add some database columns and make a couple small tweaks.
