### ISSUE TITLE
Evidence Items with two drugs are being separated into two evidence statements. 

### ISSUE THREAD

**Issue by nspies13** [genome/civic-server#20]
I think I can fix this.

**Comment by acoffman** [comment]
So, this is intentionally built into the current schema - is this no longer correct? Right now an evidence item is: descriptive text and metadata (significance, evidence level, direction, etc) that links a single variant, drug, disease, and source.

**Comment by nspies13** [comment]
This was a relatively recent change actually. The drug column can be interpreted basically as a string. And multiple drug are acceptable. Thanks. 

Nick

**Comment by acoffman** [comment]
Gotcha, will this be true of all foreign keys on evidence items then - or only drugs?

**Comment by nspies13** [comment]
Only drugs.

**Comment by acoffman** [comment]
So, Josh and I talked about this a little bit and this is a fairly major change. We can do it, but likely not before AGBT. It will require changes to the importer, a brand new table in the database, changes to all the API endpoints that deal with evidence items, changes to the add evidence item form and changes to the data grid that displays evidence items. We'll come up with a plan to tackle this next week if that works for everyone?

**Comment by nspies13** [comment]
That works. Sorry for the change!

**Comment by acoffman** [comment]
No problem at all! Just trying to get the most stuff done we can before AGBT so we're trying to prioritize what we can do in that time period.

**Comment by acoffman** [comment]
Fixed!
