### ISSUE TITLE
add 'unseen' and 'unreachable' filters/attributes to feed endpoint

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-server#200]
In order to support genome/civic-client#434, a checkbox to toggle the display of unseen notifications, I need a way to filter out unseen notifications from the API endpoint.

I'm also thinking to add an additional checkbox toggle for unreachable notifications as well so if it wouldn't take much time could you add that as well?

These can be either a filter or an attribute, whatever is easiest.

**Comment by acoffman** [comment]
Done!
