### ISSUE TITLE
Need to allow the addition/edit of disease through the admin interface.

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-server#205]
EID1441 was entered with all caps but I can't submit suggested changes to fix it because the disease doesn't exist in the database.

**Comment by kkrysiak** [comment]
Alternatively, enable the 'disease not found' checkbox to enable free form text in the suggested revisions form so anyone can do this.

**Comment by acoffman** [comment]
Disease names can now be edited and new diseases can be added in the admin panel!
