### ISSUE TITLE
Variants on sidebar remain after admin moves evidence items

### ISSUE THREAD

**Issue by ahwagner** [genome/civic-server#207]
KRAS has a "WILD TYPE" variant on the sidebar, that was likely introduced with [eid #1139](https://civic.genome.wustl.edu/#/events/genes/30/summary/variants/336/summary/evidence/1139/talk/comments). It looks like @malachig moved it to the "MUTATION" variant, but the "WILD TYPE" variant label remained behind (unclickable) without any corresponding evidence.

**Comment by malachig** [comment]
Yeah, I thought this was fixed.  But maybe I am misremembering.  Or perhaps its is waiting on the next deploy.

**Comment by acoffman** [comment]
This should be fixed on the live site now!
