### ISSUE TITLE
Revision Searches

### ISSUE THREAD

**Issue by ahwagner** [genome/civic-server#213]
I don't know if this is a planned feature or an existing bug, but you cannot search revisions using the `#R:` syntax. @kkrysiak recommended that I document this here.

**Comment by acoffman** [comment]
Yeah good catch! @jmcmichael and I considered how this might work and couldn't come up with what we'd even show as an auto-complete suggestion. I believe it will still work for linking, but it won't provide suggestions.

Any thoughts on what we'd "show" in the suggestion box for a revision? There's not really enough space to show a meaningful diff. I guess we could search the contents of the new suggested text and show that?

**Comment by kkrysiak** [comment]
Maybe the context of the revision? Revision to variant X of gene Y or EID W of variant X of gene Y? Then maybe start into the text of the revision or the revised fields??

**Comment by acoffman** [comment]
Yeah, something like that might work! I'll see what we can come up with

**Comment by acoffman** [comment]
This still seems to be only of limited utility, but it works now! The autocomplete searches the contents of the changeset and the preview text indicates the name of the entity being changed as well as the names of the fields involved in the revision.
