### ISSUE TITLE
Special consideration for variant type capitalization

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-server#223]
3 Prime Utr Variant is a bit strange. 3 Prime UTR Variant would be preferred. '5 Prime UTR Variant' and 'UTR Variant' are other alternatives that would be effected. I don't think UTR will come up very often in other contexts.

**Comment by acoffman** [comment]
Is the intent of this issue just that when `UTR` appears as a literal string in any variant name, we should uppercase it retroactively? That should be super simple if that's the case!

**Comment by kkrysiak** [comment]
That's what I'm proposing. If it is a "word" alone, all caps.

**Comment by acoffman** [comment]
Cool, that's easy enough to implement! Do you want a one time pass through the data to do this transformation, or a permanent special case for it?

**Comment by kkrysiak** [comment]
I guess it would have to be done each time variant types were pulled in from SO but should otherwise just be able to be done on the site once.

**Comment by acoffman** [comment]
Yeah, that makes sense, thanks!
