### ISSUE TITLE
"Markdown" and "Macros" for Revision Description

### ISSUE THREAD

**Issue by KujanL** [genome/civic-server#231]
These two links that illustrate how to add emphasis and formatting for references only appears when you respond to an already established comment. When suggesting coordinates, having these options listed next to the box would be helpful for users. 
This illustrates the box that shows up with the revision description:
![screen shot 2016-09-10 at 6 46 02 pm](https://cloud.githubusercontent.com/assets/15361912/18414303/d0583a6a-7787-11e6-946a-001750fb2feb.png)
This illustrates the box that shows up when responding to other comments:
![screen shot 2016-09-10 at 6 47 12 pm](https://cloud.githubusercontent.com/assets/15361912/18414306/e0f538b4-7787-11e6-8c0f-6b9a69559a7c.png)

**Comment by jmcmichael** [comment]
I've moved this issue over to civic-client (genome/civic-client#524)
