### ISSUE TITLE
Differences between API documentation and JSON response

### ISSUE THREAD

**Issue by jakelever** [genome/civic-server#236]
Hi, the example output at https://genome.github.io/civic-api-docs has some significant differences with what is actually returned. I've attached a file listing the differences, and another file with the outputs for each command (actualJSON.txt). Obviously some needed to be truncated, but all the fields should probably be shown.

Also some of the commands are mistyped, and are to https://civic.genome.wustl.edum instead of https://civic.genome.wustl.edu

[actualJSON.txt](https://github.com/genome/civic-server/files/503678/actualJSON.txt)
[differences.txt](https://github.com/genome/civic-server/files/503679/differences.txt)

**Comment by acoffman** [comment]
Thanks for the report Jake, I'll get this fixed!

**Comment by igersh** [comment]
+1 for this bug - would it be possible to fix it so all data is returned? thanks!

**Comment by acoffman** [comment]
Hi @igersh, thanks for the report!

I will definitely update the documentation to include the most current and accurate example responses, that's something that's slipped under the radar so far, but I will make sure to get done in the coming week!

As for including full evidence item information in the `/variants` index endpoint, that is unfortunately not likely in the near future. The basic design of the CIViC API involves two type of endpoints: `index` and `detail`. The `index` endpoints (such as `/variants`, `/genes`, and `/evidence_items` provide a way to page through all entities in the database and get summary information about them. The `detail` endpoints (like `/variants/:variant_id`) provide a method to drill down and see full, detailed view of a single entity.

This was a deliberate decision made to improve API performance. If, for instance, the `/variants` endpoint returned not only all of the variants, but also the complete evidence records for each variant, you could imagine the JSON response becoming large and unwieldy very quickly.

Right now, the recommended way to retrieve all the evidence records for a variant are by calling either `https://civic.genome.wustl.edu/api/variants/:variant_id/evidence_items` or `https://civic.genome.wustl.edu/api/variants/:variant_id`. The former will return only the evidence records for the variant id given, while the later will also include the variant record itself.

Let me know if you have any questions or run into any other issues while using the API! I will update this issue when a new version of the documentation is live.

Thanks again for your interest in CIViC!
Adam

**Comment by dandanxu** [comment]
Thanks Adam for looking into this - @igersh and I have been indexing CIViC on SolveBio (www.solvebio.com). We'll revert back to looping through the variants to grab the evidence id connections. Otherwise, the API has been very straightforward and easy to use!

**Comment by acoffman** [comment]
@dandanxu, that's good to hear! Would it be helpful if we included the CIViC variant ID in the evidence records directly? That would enable you to use the `/api/evidence_items` endpoint to page through all of the evidence items in bulk, and then connect them to the variants afterwards.

**Comment by dandanxu** [comment]
Yes! It would very much =). Really, any way to map between the IDs between the variant and the evidence, without looping through all of the variants individually would be useful.

**Comment by acoffman** [comment]
@dandanxu This change is now live! All evidence record responses will contain a `variant_id` which can be used to link it directly to a CIViC variant.

@jakelever Thanks for the initial report! I am working on the finishing touches to some revamped (more complete) documentation and it should go live later this evening or tomorrow.
