### ISSUE TITLE
show variant names instead of IDs in variant group suggested revisions view

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-server#238]
Currently modifications to the variants in a variant group show up as lists of numbers in the suggested revisions view, would be better for the names to be listed. This will fix genome/civic-client#405 when implemented.

![](https://cloud.githubusercontent.com/assets/8527125/14987798/997b6378-1116-11e6-909d-d4f6a73109e3.png)

**Comment by acoffman** [comment]
Fixed! Will go out in the next deploy (tomorrow).
