### ISSUE TITLE
evidence item drug revision not shown

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-server#241]
Some drug revisions not showing. See screenshot for example. It looks like a missing drug was added but the diff view does not reflect his correctly. Maybe a result of some of the behind-the-scenes edits to drugs?

![screenshot 2016-10-11 12 21 59](https://cloud.githubusercontent.com/assets/1638042/19280965/85e80c2e-8fad-11e6-8ce5-cdd3a6c1f2ac.png)

**Comment by kkrysiak** [comment]
This is my doing. Below is the suggested revision. But yesterday I merged drug ID 48 "Palbociclib (PD0332991)" and ID 371 "Palbociclib".

<img width="918" alt="screen shot 2016-10-11 at 1 30 25 pm" src="https://cloud.githubusercontent.com/assets/8527125/19283320/f8af4ff2-8fb6-11e6-8801-e45df9009157.png">
