### ISSUE TITLE
Disconnect between HGNC symbol and CIViC/myGeneInfo gene name.

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-server#242]
Strangely, COX2 is the gene name being displayed on CIViC as both an output of myGeneInfo and the official gene symbol. As I understand it, the official gene symbol should be MT-CO2 (https://www.ncbi.nlm.nih.gov/gene/?term=4513). There is some additional confusion since COX2 is the gene alias for MT-CO2 and PTGS2.

**Comment by acoffman** [comment]
Opened #244 to address the root cause of this!
