### ISSUE TITLE
Strange event stream for AR Splice Variant 7 variant

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-server#246]
When reviewing RID2873, I realized that a previous revision (RID704) should have already applied this change. Both revisions add the same representative transcript. There is a closed RID between these two that appears to have been overridden in the admin interface as it was applied despite the RID being closed and not accepted. Basically, not sure why the representative transcript was not successfully applied but RID704.

**Comment by acoffman** [comment]
I looks like the change to the representative transcript was stomped on by a subsequent change (audit log screenshot attached). It looks like it may have been performed manually in the admin interface way back in the day.

![screen shot 2017-05-31 at 5 43 53 pm](https://cloud.githubusercontent.com/assets/13370/26657348/eb7fce96-4628-11e7-9bb3-49d960bb84b1.png)

That explains the lack of a suggested change in the event stream (and the vanishing transcript).
