### ISSUE TITLE
Problems with BRAF K483M?

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#249]
I am observing various problems with the variant page for BRAF K483M.

- This variant appears in typeahead searches but nothing happens if I select it.
- If I go to the BRAF page and click on this variant, I am taken to some results but not to the URL that appears when I hover over that variant...

This is the URL I see when I hover over K483M:
https://civic.genome.wustl.edu/#/events/genes/5/summary/variants/581/summary#variant

That page does not seem to load.

In the admin interface I see pending revisions for this variant but in the UI, I can't seem to find them...

**Comment by malachig** [comment]
I am observing similar problems with B2M S14.  Again there are outstanding revisions that I can see in the admin interface but I can't seem to access them in the site:
https://civic.genome.wustl.edu/#/events/genes/537/summary/variants/616/summary#variant

I can see B2M S14 in typeahead search but selecting it does not work.

**Comment by malachig** [comment]
Also having a similar problem with JAK2 F547.  I can not access EID1568.  

Strange things happen when I try to select it.  I can view other JAK2 variants.  I can select F547, but it does not highlight on the variant name on left.  I see EID1568, but if I try to select that evidence record I get directed to another EID instead of that one...  All three of these examples I have found so far seem to follow this pattern.  All have outstanding revisions according to the admin interface that at present can not be reviewed/approved in the UI.

**Comment by acoffman** [comment]
This looks like it was an issue related to the new MyVariantInfo data that popped up when we had proper coordinates with which to query the API but didn't receive an expected response back. I've fixed the issue and these links all seem to be working now!

**Comment by malachig** [comment]
Confirmed.  All of the problems I was having related to these appear to be resolved now.  Thanks!
