### ISSUE TITLE
Update Clinical Significance values for Predisposing evidence to use ACMG values

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#255]
Currently we use `Positive` and `Negative` for `Clinical Significance` values but it would make more sense to use the nomenclature from the ACMG guidelines for `Predictive` evidence:

https://www.acmg.net/docs/Standards_Guidelines_for_the_Interpretation_of_Sequence_Variants.pdf

From Table 5:
- Pathogenic
- Likely pathogenic
- Benign
- Likely benign
- Uncertain significance

**Comment by acoffman** [comment]
@malachig This is straightforward to do on our end! Is there a conversion we can use for our existing values? Or should we introduce these new values alongside our existing ones?

**Comment by malachig** [comment]
Lets just set the few we have to NULL and we will manually select the right answer for each and have these reviewed by editors.

**Comment by acoffman** [comment]
(notes for myself)

This will be a little tricky as its stored as an enum, so we can't just remove these values right off the bat. We'll need to add the new ones at the end of the enum and overwrite the existing values to null. Then in a subsequent migration we'll want to left shift everything by two and delete the old values in the middle of the enum.

**Comment by malachig** [comment]
This sounds like a good approach to me.
