### ISSUE TITLE
support clinvar ID as a property on variant

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-server#265]
In some cases it is impossible to get to a clinvar record through myvariant.info (non simple variants). We would like to be able to add these to the variant record in such cases.

**Comment by acoffman** [comment]
Would this be a standard curated field like any other? That should be easy to add! Is it safe for the schema to assume a single CIViC variant will map to only one ClinVar variant? How about the reverse (a ClinVar variant will map to only a single CIViC variant)?

**Comment by malachig** [comment]
I think we want to support many-to-many.  A single CIViC variant could map to multiple ClinVar records because some of our variants that are generic.  I wouldn't generally expect the reverse to be true, but I'm sure it is possible.
