### ISSUE TITLE
Support Filtering on Gene Index Endpoint

### ISSUE THREAD

**Issue by acoffman** [genome/civic-server#267]
Right now we support either paging through the entire set of genes in civic via the `/genes` endpoint or retrieving detailed information for a single gene via the `/genes/:identifier` endpoint.

A user has requested that we allow for the retrieval of multiple specified genes in a single query of the format: `/genes/TP53,BRAF?identifier_type=entrez_symbol`

This should be straightforward to implement. One outstanding question is the desired behavior if not all members of the list are found. Should results be returned for identifiers that _are_ found and the others dropped? Or should the whole request `404` so the user knows there was an issue with one or more list items? I'm currently leaning towards the former.

**Comment by Sjoerd-van-Hagen** [comment]
Hi Adam,

Thanks a lot for picking this up!

I would prefer the approach that the ones that are found are listed. In that case you can argue that it works as a filter on the genes. The problem with a 404 is that you would have to redo the call based on the response body that should then list the ones that are not available. I think this makes it more complicated both on the server as on the client side.

Best,

Sjoerd.

**Comment by acoffman** [comment]
This will go out in this week's deploy! Thanks again for the report.

**Comment by Sjoerd-van-Hagen** [comment]
Great!

Thanks for the quick implementation.

**Comment by acoffman** [comment]
Hi @Sjoerd-van-Hagen,

This endpoint is now live on the production instance of CIViC! Please do let me know if you encounter any issues or have any other feature requests!

Adam

**Comment by Sjoerd-van-Hagen** [comment]
Hi Adam,

It all works great, so many thanks for that.

There are some cases where we need to retrieve a large number of variants,
1200 or more. At this point we reach the maximum allowed length for a URL.
OncoKB circumvents this by allowing POST requests. Would it be possible to
have this for Civic as well?

Best regards,

Sjoerd.
