### ISSUE TITLE
Document ways to link to CIViC records

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#268]
We recently added new methods to allow simpler URLs for genes, variants and evidence.

I can't remember the format of these shorter URLs and could not find it documented in the site.  Should we document it on the API docs pages?

**Comment by malachig** [comment]
It looks like the content of such documentation is already pretty fleshed out in this closed issue on the client side:
https://github.com/genome/civic-client/issues/531

**Comment by acoffman** [comment]
We definitely should! I'm in the process of updating the documentation for #236 and #267, so I will do this simultaneously with that update!

**Comment by acoffman** [comment]
This is complete and will go out today!
