### ISSUE TITLE
Incorrect Glossary of Terms enteries

### ISSUE THREAD

**Issue by CodyRamirez** [genome/civic-server#273]
The glossary definitions for **Evidence Level C** and **Evidence Level D** are switched here https://civic.genome.wustl.edu/#/glossary

Correct definitions are below:
**Evidence Level C**
Case study evidence from individual case reports in peer reviewed journals.

**Evidence Level D**
Preclinical evidence from cell line studies, mouse models, and other in vitro or in vivo models.

**Comment by malachig** [comment]
Fixed via: https://github.com/genome/civic-server/commit/041960a010e58cf002be3c7561b9b841705c58d5
