### ISSUE TITLE
Publication authors not being pulled in?

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-server#274]
Author list is missing for a number of sources. See example below.
https://civic.genome.wustl.edu/#/sources/1251/summary

**Comment by acoffman** [comment]
Sometimes when the request to the PubMed API fails for whatever reason (timeout, incomplete response, issue on our end, etc) we don't get the full author list, but we don't want to fail the whole request as we still want to capture the submission.

I've added a task that will run daily and go through publications with incomplete metadata, filling in missing fields as needed.
