### ISSUE TITLE
ClinVar clinical significance not being pulled in

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-server#275]
This may just be a disconnect between ClinVar and MyVariant.Info as far as updates but I noticed that this variant https://civic.genome.wustl.edu/#/events/genes/4244/summary/variants/262/summary/evidence/674/summary#evidence has a ClinVar ID that has a clinical significance of "Benign" but the MyVariant.Info box has "-".

**Comment by kkrysiak** [comment]
Corresponding clinvar record https://www.ncbi.nlm.nih.gov/clinvar/variation/166619/

**Comment by acoffman** [comment]
This looks like a client issue, so I've opened one there. Basically sometimes MyVariantInfo gives us back a list and sometimes a single object, and currently only one of the cases is being addressed.
