### ISSUE TITLE
Missing sequence ontology term

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-server#276]
I'm trying to revise UGT1A1*28 to change the Variant Type from "microsatellite (SO:0000289)" to the more specific "dinucleotide_repeat_microsatellite_feature (SO:0000290)" but I can't find that option. Strangely I do get presented with an even more specific child term "GT_dinucleotide_repeat (SO:0001862)". 

<img width="1215" alt="screenshot 2017-01-20 17 51 57" src="https://cloud.githubusercontent.com/assets/1638042/22169367/308a51d4-df39-11e6-8f96-fdbb2b4d9456.png">

**Comment by acoffman** [comment]
Looks like our version of the sequence ontology may be out of date. I'll update it manually and hopefully we'll roll out our auto-updating data sources in the next week!

**Comment by acoffman** [comment]
Two things were going on here. 1.) our version of the sequence ontology was out of date, and 2.) our importer was only importing SO terms that had a definition. This one doesn't and as such it wasn't pulled in.

I've updated the importer to pull in all terms, even if lacking a definition, and when we deploy, we will start automatically updating the sequence ontology weekly.
