### ISSUE TITLE
Search list does not correctly sort by evidence level upon first loading. 

### ISSUE THREAD

**Issue by nspies13** [genome/civic-server#277]
https://civic.genome.wustl.edu/#/search/evidence/d60ce0df-6fdb-4417-80ec-71b4a18dc2e9

EL shows the arrow, but the list is not sorted until I actually click it to cycle through sort features.

**Comment by acoffman** [comment]
@jmcmichael and I took a look at this and it appears to be a client side issue. He's created genome/civic-client#646 to address it!
