### ISSUE TITLE
Diseases without a DOID are becoming new and separate entries despite being identical

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-server#278]
I think this is similar to what happened previously with drugs. Lynch Syndrome and von Hipple Lindau being obvious examples. I could merge these but this could probably be handled more easily programmatically.

Also, is this contributing to our disease count?

<img width="932" alt="screen shot 2017-01-23 at 9 53 38 am" src="https://cloud.githubusercontent.com/assets/8527125/22211282/301a3b54-e152-11e6-8e11-f1637e54b057.png">

**Comment by kkrysiak** [comment]
I also noticed an "empty" disease. Not sure how that happened/was allowed. It doesn't appear to have any EIDs associated with it though. https://civic.genome.wustl.edu/admin/diseases/2151

**Comment by acoffman** [comment]
This issue is fixed in master, and once we deploy I will merge these all programatically! I've also added a merge tool to the admin interface in case it comes up again somehow (it shouldn't hopefully).
