### ISSUE TITLE
Request additional DOID items to be added to our custom list from them

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-server#279]
Lynch Syndrome (DOID:3883)
Von Hippel-Lindau (DOID:14175)
Renal Cell Carcinoma - there are 2 entries that can be merged one with and one without a DOID.
NSCLC - there are 2 entries (Non-small Cell Lung Carcinoma and NSCLC) that can be merged.

I suppose this also introduces the thought of creating a disease merge utility.

**Comment by acoffman** [comment]
This should be all done!

* All entries for Lynch Syndrome merged into one and the DOID filled in
* All entries for Von Hippel-Lindau merged and the DOID filled in, also renamed slightly to match whats in the Disease Ontology.
* Renal Cell Carcinoma appears to have already been merged. There's one entry and it has a DOID
* NSCLC merged into Non-small Cell Lung Carcinoma and the DOID is filled in.

Disease merge utility is also live on the admin panel.
