### ISSUE TITLE
Add HGVS

### ISSUE THREAD

**Issue by nspies13** [genome/civic-server#28]
And by HGVS I mean use chr:start-stop (ref -> var)

**Comment by kkrysiak** [comment]
Resolved for SNVs in DoCM. Still need to figure out other variants (fusions, exon level, amplifications). Add N/A for expression changes.

**Comment by malachig** [comment]
In our latest meeting we decided that a *single* representative coordinate should be added at the *variant* level instead of the evidence item level.  This would include: build, chr, start, stop, ref, var, representative transcript, chr2, start2, stop2.

**Comment by acoffman** [comment]
Closing as duplicate of #143
