### ISSUE TITLE
Typo in pending revisions

### ISSUE THREAD

**Issue by agraubert** [genome/civic-server#283]
The pending revisions alert reads `Variant aliass`
You can view the typo [here](https://civic.genome.wustl.edu/#/events/genes/4244/summary/variants/451/summary#variant) by hovering over the variant revisions alert

The typo is somewhere in the backend, and is present in the [return data from the api](https://civic.genome.wustl.edu/api/variants/451/fields_with_pending_changes)
I tried looking through the server code, but I couldn't find the source of the typo

**Comment by acoffman** [comment]
Nice catch!

Basically the code that does this takes all the field names with pending changes and then slices off `_id` if its there. Those values had `_ids` in the attribute name, and thus the substitution took `variant_alias_ids` => `variant_aliass`, I've corrected it to  remove the extra `s` when present.
