### ISSUE TITLE
utilities page of admin interface will not load

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#285]
I wanted to merge duplicate accounts for arpad and noticed that the utilities page throws an error:

![screen shot 2017-01-30 at 7 01 59 pm](https://cloud.githubusercontent.com/assets/856728/22448373/9dc154fe-e71e-11e6-9cff-b268816295c8.png)

**Comment by acoffman** [comment]
This is corrected and I've merged arpad's accounts as discussed in the slack channel!
