### ISSUE TITLE
typeahead results should include all fields searched

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-server#29]
So on the typeahead results, I'd like to show the matching text in the dropdown but it looks like some of the fields searched are not returned in the results. For example if I search for 'nib':

http://localhost:3001/api/variants/typeahead_results?query=nib

I get a bunch of hits but the drug field, which I assume which has all the hits on 'nib', isn't returned in the results.

Also if it's not too difficult or computationally expensive, it would be cool to have would be a list of field(s) that contain the searched string. So if I type in 'BRAF' then I get all the BRAF variants and a 'hits' field that might be ['entrez_name']. If I search for 'nib', the 'hits' field would be ['drug']. Then I can include that info in the dropdown.

**Comment by acoffman** [comment]
done! bdedcc312c5495f3b21bf878aa06ab4902ca7c84
