### ISSUE TITLE
Revisions not linking in comments

### ISSUE THREAD

**Issue by agraubert** [genome/civic-server#292]
Oddly enough, it's working fine on my local server, but the live site is definitely not returning the links properly in the markdown.
My guess is that it's coming from the [suggested changes link adapter](https://github.com/genome/civic-server/blob/master/app/presenters/link_adaptors/suggested_change.rb) but without access to the live server, I can't really tell.

Malachi and Obi originally identified this issue in genome/civic-client#582 and genome/civic-client#682

Markdown returned from the live server
<img width="335" alt="screen shot 2017-02-08 at 10 47 01 am" src="https://cloud.githubusercontent.com/assets/997749/22747307/5e5b4c50-edec-11e6-9f4b-49caf7c8225d.png">

And from my local server
<img width="807" alt="screen shot 2017-02-08 at 10 47 24 am" src="https://cloud.githubusercontent.com/assets/997749/22747326/672e26f4-edec-11e6-8457-2a574536af6e.png">

**Comment by acoffman** [comment]
This is super weird. Its working fine locally for me, @agraubert, and also in the console on the prod server. For some reason its not working correctly only in the production server environment. I've added a workaround that seems to have fixed it; but I'm still not sure what the issue actually was.
