### ISSUE TITLE
some endpoints need gene ids to be returned from add/accept/reject endpoints to perform cache flush/refresh actions on variant_statuses

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-server#295]
The variant menu changes/evidence indicators need to be updated after any variant add/accept/reject and evidence add/accept/reject the variant accept/reject and evidence add responses return a gene_id, but the following endpoints don't provide a gene id:

`POST /api/variants/:variantId/suggested_changes/`
`POST /api/evidence_items/:evidenceId/accept`
`POST /api/evidence_items/:evidenceId/reject`

**Comment by acoffman** [comment]
All of these endpoints should now include the gene id in the response!
