### ISSUE TITLE
Searching by variant start/stop behaves unexpectedly

### ISSUE THREAD

**Issue by agraubert** [genome/civic-server#296]
All the data fields are stored as text in the sql, so searching for `start < 4` is doing a lexicographical sort as opposed to a numerical sort.

[Here's the search I used](https://civic.genome.wustl.edu/#/search/variants/b7da0f58-d250-4301-90fb-e5b1153683d1), which returns every variant with a start coordinate that starts with a 1, 2, or 3 as opposed to variants starting before the 4th nt

**Comment by acoffman** [comment]
Yeah, good catch. This is actually a result of this: https://github.com/genome/civic-server/issues/83 issue not being fixed yet. It shouldn't be too hard of a fix, just need to actually do it. Something along these lines in a migration would work: http://stackoverflow.com/questions/13170570/change-type-of-varchar-field-to-integer-cannot-be-cast-automatically-to-type-i but we'd want to do some pretty serious local testing before rolling it out in production.

**Comment by agraubert** [comment]
Oh, oops! I didn't see the existing open issue

**Comment by acoffman** [comment]
No problem! You're welcome to try and tackle it if you're feeling ambitious, otherwise I'll try to get to it next week myself! Its been sitting in the backlog long enough haha.

**Comment by agraubert** [comment]
I'm actually working on something similar for pVAC-Seq, which is why I stumbled on this in the first place.  Although my solution is going to be more of casting data as it's inserted rather than casting existing data, so I'm not sure it'll help CIViC

**Comment by acoffman** [comment]
Variant coordinates are now compared numerically in the database and the advanced search works in a more intuitive manner. I'll finish off the rest of #83 on that thread.
