### ISSUE TITLE
Typo in civic bot submissions for chromosome 10

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#297]
Depending on how many of these there are, we can probably just fix these as we are curating.  But I wanted to report it so that the code could be corrected for future.

It looks like HGVS suggestions from CIViC bot for chromosome 10 variants have a typo in the accession for chromosome 10.  e.g.
https://civic.genome.wustl.edu/#/events/genes/41/summary/variants/636/talk/revisions/list/4036/summary#variant

`NC_000010.100:g.89692904C>T` should be `NC_000010.10:g.89692904C>T`.

**Comment by acoffman** [comment]
Good catch, it looks like a copy/paste error when I copied the accession mappings from here: https://www.ncbi.nlm.nih.gov/assembly/GCF_000001405.25

A couple of the accession numbers picked up the last column somehow. I've fixed the script used to generate these, and if you start finding more than just a handful of of them, I can void out the suggestions that haven't been accepted yet and re-run it; just let me know!

**Comment by ahwagner** [comment]
https://civic.genome.wustl.edu/events/genes/20/summary/variants/36/talk/revisions/list/3881/summary#variantCIViC bot seems to think that NC_000017.10 is NC_000017.104.

**Comment by acoffman** [comment]
@ahwagner yeah, there were a couple of accessions that were copy-pasted incorrectly, I'm just waiting for the go-ahead to delete the existing ones so I can regenerate!

**Comment by acoffman** [comment]
This has been fixed in the latest run of civic bot!
