### ISSUE TITLE
The importer didn't throw an error on missing DOIDs

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-server#30]
When I merged in the coordinate information, I made a mistake and we lost the leading zeros on a handful of DOIDs again. This resulted in evidence items without an associated disease (18 to be exact).

**Comment by acoffman** [comment]
Good catch, I'll take a look!

**Comment by acoffman** [comment]
Do we have the DOIDs corrected in the import spreadsheet yet? If not, I can tackle that.

**Comment by kkrysiak** [comment]
I did that as soon as I noticed the problem. Nick is doing some additional changes to the google spreadsheet. I told him to comment here when he's finished.

**Comment by acoffman** [comment]
Awesome, thanks!

**Comment by acoffman** [comment]
Fixed!
