### ISSUE TITLE
illumina import caused an influx of disease entries in the admin interface

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-server#301]
It doesn't hurt our count on the main page or anything but it hurts the utility of the disease list in the admin interface.
<img width="1085" alt="screen shot 2017-04-11 at 10 16 20 am" src="https://cloud.githubusercontent.com/assets/8527125/24916505/f660fee4-1e9f-11e7-8fac-ccb0812a29ef.png">

**Comment by kkrysiak** [comment]
Related, I guess we missed the mapping of "Mesothelioma (malignant, Clinical Disorder)" to malignant mesothelioma (DOID:1790). This is one of the highly propagated diseases.

**Comment by kkrysiak** [comment]
Also, some NULL values got introduced in this import. That makes me a bit worried but none of the NULL disease entries I've clicked on thus far have had EIDs assigned to them but do seem to be in the type ahead.

<img width="1068" alt="screen shot 2017-04-11 at 4 17 33 pm" src="https://cloud.githubusercontent.com/assets/8527125/24931312/6e36d452-1ed2-11e7-893d-f0346dfb58a3.png">
<img width="1166" alt="screen shot 2017-04-11 at 4 17 06 pm" src="https://cloud.githubusercontent.com/assets/8527125/24931313/6e3857be-1ed2-11e7-9635-e7bb1c1fcc3f.png">

**Comment by acoffman** [comment]
- [ ] Investigate and cleanup NULLS
- [ ] Clean up duplicate disease entries
- [ ] Map  "Mesothelioma (malignant, Clinical Disorder)" to malignant mesothelioma (DOID:1790)
