### ISSUE TITLE
display organization on user profile and cards

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-server#305]

**Comment by acoffman** [comment]
- [ ] Organizations table and foreign keys exist
- [ ] Organizations models exist
- [ ] Admin ui exists for creating/assigning members to organizations
- [ ] Community page can be filtered by organization name
- [ ] Event stream can be filtered by organization
- [ ] Include organization information on user endpoint
- [ ] Organizations can have profile pictures (manual admin process at first)

**Comment by acoffman** [comment]
@jmcmichael 

I'm still working on the profile image stuff, but the rest is good to go.

* User objects will now have an organization object attached (if they belong to one)
* The community page accepts a text filter for organization name in the form of `filter[organization]=blah`
* The endpoints `/api/organizations`, `/api/organizations/:id` and `/api/organizations/:id/events` exist and work as expected.
* There is functionality in the admin backend to create orgs and assign users to them.

**Comment by acoffman** [comment]
I'm sure we'll want to revisit and expand the organization functionality going forward, but the initial version is out and functional so I'm going to close this.
