### ISSUE TITLE
add /curation endpoint, with /curation/flags as the initial data type provided

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-server#310]
In prep for a full-featured curator dashboard, let's add a endpoint that returns all open flags. This can drive an 'Open Flags' page for admins that will then shift to a more complete dashboard page after more /curation endpoints are added.

**Comment by acoffman** [comment]
`/curation/open_flags` now returns a standard paginated style endpoint of `flag` objects for all open flags.
