### ISSUE TITLE
create variants_status endpoint focused on data required to render variant-menu

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-server#319]
This should reduce the number of queries made to the server for gene and variant summary view currently required to display the variant menu.

Request:
`/api/gene/:geneId/variants_status`

Response:
``` typescript
{
  variants: [
    {
      id: number,
      name: string,
      gene_id: number,
      coordinates: {
        chromosome: string,
        start: number
      },
      evidence_item_statuses: {
        accepted_count: number,
        rejected_count: number,
        submitted_count: number
      },
      status_counts: {
        pending_evidence_count: number,
        pending_fields_count: number
      }
    } 
  ],
  variant_groups: [
    {
      id: number,
      name: string,
      variants: [
       // (same objects as root variants list)
      ]
    }
  ]
}
```

**Comment by jmcmichael** [comment]
I guess we don't need evidence_items for variant object as I can add up the values in evidence_item_statuses to get that.

**Comment by jmcmichael** [comment]
Added chromosome_position attribute. If this is possible, it will allow the addition of the 'sort by' menu requested in genome/civic-client#630. Additionally, if we can replace statuses has_pending_evidence, and has_pending_fields, I can also use those to sort by pending evidence and pending fields as well as driving the display of the notification ! icon.

**Comment by acoffman** [comment]
This is pushed to master, as spec'd here!
