### ISSUE TITLE
include 'provisional' summary in gene and variant endpoints if submitted but unaccepted summary exists

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-server#322]
Also should include summary's revision ID so a link to the revision can be included.

Required to implement genome/civic-client#464

**Comment by acoffman** [comment]
@jmcmichael How do you want this to be denoted in the response object? A new field of some sort I assume?

**Comment by jmcmichael** [comment]
Maybe we should have a provisional_values object like:

```
{
...
  provisional_values: {
    summary: {
       value: string,
       revision_id: number
    },
    [additional provisional values]
  }
...
}
```

Initially we'd just include the summary, but could later drop in other values if we wanted to provisionally display additional fields that have pending but unapproved values.

**Comment by jmcmichael** [comment]
(updated to change 'summary' to 'description' as the provisional fields should have the same key as the actual field at the root of the returned object)

**Comment by acoffman** [comment]
This is completed and pushed for gene and variant summaries. We can add additional fields as needed!
