### ISSUE TITLE
after deleting a variant, performing a feed request with show_unlinkable=true returns 500 error

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-server#325]
While setting up a test for genome/civic-client#756, I deleted a variant w/ a bunch of comments them hit the notifications page. The notifications page loaded fine the first time, but when I clicked 'show unlinkable' and the client made the following request:

/api/current_user/feed?category=subscribed_events&count=10&filter%5Blimit%5D=all_time&page=1&show_read=false&show_unlinkable=true

the server returned the following error:

NoMethodError at /api/current_user/feed
=======================================

> undefined method `subscribable_name' for nil:NilClass

app/presenters/subscription_presenter.rb, line 17
-------------------------------------------------

``` ruby
   12           created_at: sub.created_at,
   13           updated_at: sub.updated_at,
   14           subscribable: {
   15             type: sub.subscribable_type,
   16             id: sub.subscribable_id,
>  17             name: sub.subscribable.subscribable_name,
   18             state_params: sub.subscribable.state_params
   19           }
   20         }
   21       else
   22         {}
```

App backtrace
-------------

 - app/presenters/subscription_presenter.rb:17:in `as_json'
 - app/controllers/notifications_controller.rb:48:in `generate_index'
 - app/controllers/notifications_controller.rb:4:in `index'
 - app/middleware/cross_origin_request.rb:7:in `call'

**Comment by acoffman** [comment]
It turns out that deleting something via a soft_delete wouldn't trigger the correct cleanup callbacks and we'd end up with active subscriptions to things that had been soft deleted. Soft deletes will now trigger the appropriate callbacks!
