### ISSUE TITLE
variants_status includes extraneous variants for KIT Exon 11 Group

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-server#327]
As noted in genome/civic-client#762, the variant menu for KIT shows extraneous variants within its KIT Exon 11 Group. The server appears to be including these repeated variants, see:

https://civic.genome.wustl.edu/api/genes/29/variants_status

**Comment by acoffman** [comment]
The existing data has been fixed and the server will no longer allow duplicate members in a variant group.
