### ISSUE TITLE
ALK F1174L has a leading comma in disease column

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-server#35]
Problem with data or import?  Looks like there is an empty disease term causing a leading comma on the browse page for ALK F1174L

**Comment by acoffman** [comment]
This is a dupe of #30 - some of the leading "0"s on the doid got dropped in the google doc, so it wasn't a valid DOID and we were unable to find a name. Its not a bug per se but the importer should probably be noisier about it when it happens!
