### ISSUE TITLE
check out prerender_service and prerender_rails for generating static crawler-friendly pages

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-server#37]
One of the downsides of single page applications (SPAs) is that in order to be viewed they must be generated by javascript, and most search engine crawlers cannot do this. The workaround is for the server to return the SPA for users and static rendered pages for web crawlers. Google has created a set of standards for doing this, and it's also baked into AngularJS as well. More details at [Google's Making AJAX Applications Crawlable](https://developers.google.com/webmasters/ajax-crawling/) page.

Given that one of the goals of CIViC is to be a useful online reference for cancer variant information, we should make it easily available to search engines, etc.

A company, prerender.io, provides software for doing the redirection and page generation logic. They've open sourced their software so it's possible to install and set up your own prerender server. Then you use their Rails libraries to plug it into your app.

I found this after digging around for a little bit, and it looks like the easiest solution. Here's Prerender.io:

https://prerender.io/

Their node-based page rendering server:

https://github.com/prerender/prerender

And the Rails gem that generates the rendering requests and serves up the prerendered pages:

https://github.com/prerender/prerender_rails

**Comment by malachig** [comment]
+1 this is a really good point.  being able to search for and find the variant level summaries in particular could wind up being *the* major source of daily users.  But for that to work we obviously need search engine indexing...

It sounds like the functionality of prerender might do the trick.  And by luck they have selected the same MIT license as us for their project, which is also nice.

**Comment by jmcmichael** [comment]
Google effectively indexes all of our pages, so this solution doesn't seem as urgently required anymore. Additionally, Angular2 has been architected to provide server-side rendering without all of these complex solutions required by angular 1, so with the version 2 of the client it may be possible to have rendered static pages much easier, if required.
