### ISSUE TITLE
variants endpoint needs gene aliases returned

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-server#39]
The new browse-by-gene mode can have an 'aliases' column for each gene, but the server doesn't return these from the /variants endpoint, can we get aliases for each gene as well?

[Issue #35 over in civic-client](https://github.com/genome/civic-client/issues/35)

**Comment by malachig** [comment]
The 'aliases' should be taken verbatim from Entrez gene (via MyGeneInfo) as we do with the long gene names and description.

**Comment by acoffman** [comment]
So have we decided we are going to track gene aliases? That will require some importer changes and a new database table. We're currently only storing the entrez id, symbol and clinical description. Everything else is pulled dynamically from MyGene.info on page load.

**Comment by malachig** [comment]
Yeah, I think it would be very helpful to be able to view them in the data grid and filter on them in that view.

If it is a pain to update the schema/importer, I guess we could store the aliases as a simple string in the same table as symbol and clinical description?  

Unlike the gene symbols these aliases can be reused in different contexts.  Furthermore, there is to my knowledge no additional information associated with each alias.  But I could be wrong there.  I believe the list of aliases for each gene entry is the product of fairly manual curation by the Entrez team.

I can't think of any need for them to be accessed individually right now... but that could change I guess.  

Up to you @acoffman on how best to modify the schema.

**Comment by obigriffith** [comment]
I think the main application is that when doing a live search of HER2 or other aliases the system is smart enough to show not only genes that match that string but also genes that have it as an alias.

**Comment by acoffman** [comment]
Cool, are gene aliases guaranteed to be unique to a single gene?

**Comment by obigriffith** [comment]
Unfortunately not. It is possible that two genes with different gene symbols (that are guaranteed to be unique) might share the same synonym. And, in some cases a synonym of one gene might actually be the unique symbol of another gene.

**Comment by malachig** [comment]
And that is where the manual curation comes in.  Entrez has assigned a unique symbol to each gene locus.  They have then curated the literature to find places where alternate names are used to refer to particular genes.  In the very common case where a colloquial name for a gene is used they try to determine which unambiguous gene they are likely referring to.  Then then add that synonym to the possible alternate names for the appropriate gene.

**Comment by acoffman** [comment]
Gotcha, so from a data model perspective, this is a many-to-many. A gene can have many synonyms (obviously), but a synonym could also potentially refer to multiple genes.

**Comment by obigriffith** [comment]
Correct.

**Comment by acoffman** [comment]
Done in b88e06c3b834a1abc77b4a76e1e0c36120bb5d56. You'll need to reimport to see any aliases as the scraping is done at that point!
