### ISSUE TITLE
Error on Edit Variant Admin page 

### ISSUE THREAD

**Issue by nspies13** [genome/civic-server#42]
![screenshot 2015-03-09 08 24 15](https://cloud.githubusercontent.com/assets/4623661/6555716/0ab1b470-c636-11e4-8ff8-11f87b676a99.png)

**Comment by acoffman** [comment]
Do you recall if you were trying to view a specific variant or perform a specific action that triggered the failure? Or was it just viewing the general Variants index page?

**Comment by nspies13** [comment]
I was trying to edit the new variant. LYN D189Y.

**Comment by acoffman** [comment]
Fixed!
