### ISSUE TITLE
implement REST API versioning?

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-server#43]
We're planning on making some breaking changes to the API, and I was thinking about the best way to handle this so that we don't have to worry too much about pushing our changes on the client and server at the same time for this and future versions. Working on different branches helps, but implementing an API versioning feature would pretty much eliminate the problem.

I was thinking from the API side the easiest way to do it would be to place a version slug in the URL like:

http://127.0.0.1:3001/api/v1/[...]

Looks like there's at least one gem that provides this feature:

https://github.com/bploetz/versionist

and a few articles that show how to roll your own:

http://www.bignerdranch.com/blog/adding-versions-rails-api/

**Comment by acoffman** [comment]
Yup, I've done this for both DGI and Docm, so we should definitely do the same here!

**Comment by bainscou** [comment]
+1

**Comment by acoffman** [comment]
I'm going to close this issue for the sake of tidiness. Once we're officially out of beta we'll pin the API at v1 and from that point on, any breaking changes will require a new "version."
