### ISSUE TITLE
genes/:geneId/variant_groups returns multiple instances of the same variant

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-server#50]
To reproduce, query this URL:

http://127.0.0.1:3000/api/genes/38/variant_groups

and look for the four identical instances of D842V. The genes/:geneId route returns a gene record w/ a variant_groups array that looks correct.

In the client, this results in multiple identical entries in the Variant menu:

http://127.0.0.1:3001/#/events/genes/38/summary/variants/97/summary

(This issue is linked from genome/civic-client#77)

**Comment by acoffman** [comment]
Taking a look!

**Comment by acoffman** [comment]
Fix pushed to master!
