### ISSUE TITLE
add an applied_by attribute to suggested_changes objects?

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-server#55]
I'm thinking that having an 'Applied by' column in the entity revisions lists would be good to have, and I bet we get asked for it eventually. Could we add an 'applied_by' attribute to objects returned from the various entities' suggested_changes endpoints? It might then make sense to change name of the 'user' attribute to 'created_by'. I don't consider this to be a high priority request, just thought it would be a good enhancement and didn't want to forget it.

**Comment by jmcmichael** [comment]
OK, this might be premature optimization, but in order to support multiple revision states possibly with different users moving them into/out of those states, perhaps we should have a 'users' attribute that contains an object like:

```json
"users": {
  "created": { "name": "Bob", "..." },
  "applied": { "name": "Alice", "..." },
  "some_future_state": { "name": "Carol", "..." }
}

**Comment by acoffman** [comment]
This issue has been superseded by the lifecycle events stuff. Going to go ahead and close it.
