### ISSUE TITLE
Add more information to tables in Admin interface

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#56]
Here are some values and other changes that I found myself wanting in the admin interface:

- In the `Comments` view show: `Commentable` and `Commentable Type` values
- In the `Evidence Items` view set default sort to be reverse chronological on the `Updated At` field.
- In the `Evidence Items` view add the `Evidence Level` field
- In the `Evidence Items` view in the `Filters` section, the `Variant` drop down menu should be sorted by variant name. The remaining values that you can filter on could all also be drop down menus as well.
- In the `Variants` view it would be good to have the 'Updated At' field so that one can quickly find the latest variants that were added.
- In the `Variants` view in the `Filters` section the drop down menu for `Gene` should be sorted by Gene name.  I would also make this the first filter listed instead of the last one.
- In the `Variants` view, when you edit a variant ideally you should be able to edit coordinate information perhaps.
- In the `Genes` view, perhaps the default sort should be by `Updated At`.  Same thing for the `Suggested Changes` view.
- It was not immediately clear how one would create a `Subscription`.  Maybe we should have some examples in here or further guidance on how to create these?

**Comment by acoffman** [comment]
All of these are completed and pushed except the subscription and coordinate ones. I'll address them in other issues. These changes should go out in tomorrow's deploy!
