### ISSUE TITLE
When adding new evidence items, the drug that I entered doesn't appear in the resulting entry

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#60]
If I add an evidence item following the example documented in the interface (latest pull of everything).  I am able to approve this new entry in the admin interface.  Then I get an evidence item that appears in the UI and for the most looks correct.  But the drug value remains blank (even though I added one).  

Related to #59, since the admin interface only shows a subset of values for an evidence item, I can't tell if the drug was actually entered in the database successfully and just isn't display or whether it was not captured at all at the time of entry.

If I try to edit the evidence item and add a drug, that also doesn't seem to work.

**Comment by acoffman** [comment]
Fixed!
