### ISSUE TITLE
Deleting an evidence item breaks the admin interface

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#61]
If I enter one or more new evidence items and then delete one of them in the Admin interface, it seems to break the Admin interface.  It might be the same if I had deleted an evidence item that was already there from the bulk import.  After deletion the Admin interface has trouble with `descriptionapp/presenters/event_presenter.rb` see screenshot below.  

It does this from this point on unless I blow away the database and start fresh.

![screen shot 2015-06-02 at 9 56 53 am](https://cloud.githubusercontent.com/assets/856728/7938971/0fcb88ee-090e-11e5-9b75-9680287c9c27.png)

**Comment by acoffman** [comment]
Fixed in master!
