### ISSUE TITLE
evidence item's clinical significance field returns N/a instead of N/A

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-server#62]
In troubleshooting genome/civic-client#129, I discovered that if an evidence item has N/A selected for Clinical Significance, the server returns N/a instead of N/A. This causes the select element to show up blank since it fails to find the N/a value in the options array and just shows a blank select.

**Comment by jmcmichael** [comment]
This also happens for 'Resistance Or Non-response' which I have set to 'Resistance or Non-Response' on the client. Could you change that to 'Resistance or Non-response'? I'll update the client as well.

**Comment by acoffman** [comment]
Ah yeah - good catch! That's related to my recent enum changes. I'll put them back how they were (N/A and Resistance or Non-response).

**Comment by acoffman** [comment]
fixed on both counts!
