### ISSUE TITLE
Unable to start ./bin/delayed_job

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#71]
When I try this: `./bin/delayed_job start`, nothing seems to happen and no warnings are displayed.  But the service doesn't start and I get this error message in the development log:

```
2015-07-11T15:16:31+0100: [Worker(delayed_job host:Malachis-MacBook-Pro.local pid:2155)] Starting job worker
  Delayed::Backend::ActiveRecord::Job Load (2.4ms)  UPDATE "delayed_jobs" SET locked_at = '2015-07-11 14:16:31.683357', locked_by = 'delayed_job host:Malachis-MacBook-Pro.local pid:2155' WHERE id IN (SELECT  "delayed_jobs"."id" FROM "delayed_jobs" WHERE ((run_at <= '2015-07-11 14:16:31.660944' AND (locked_at IS NULL OR locked_at < '2015-07-11 10:16:31.661063') OR locked_by = 'delayed_job host:Malachis-MacBook-Pro.local pid:2155') AND failed_at IS NULL)  ORDER BY priority ASC, run_at ASC LIMIT 1 FOR UPDATE) RETURNING *
2015-07-11T15:16:31+0100: [Worker(delayed_job host:Malachis-MacBook-Pro.local pid:2155)] Job ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper (id=2) RUNNING
  Source Load (0.4ms)  SELECT  "sources".* FROM "sources" WHERE "sources"."id" = $1 LIMIT 1  [["id", 2]]
[ActiveJob] [FetchSourceCitation] [695171b1-c504-4b9f-a8b5-d230cc24fb1c] Performing FetchSourceCitation from DelayedJob(default) with arguments: gid://civic-server/Source/2
[ActiveJob] [FetchSourceCitation] [695171b1-c504-4b9f-a8b5-d230cc24fb1c]    (1.0ms)  BEGIN
[ActiveJob] [FetchSourceCitation] [695171b1-c504-4b9f-a8b5-d230cc24fb1c] PG::ProtocolViolation: FATAL:  invalid frontend message type 1
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
: BEGIN
[ActiveJob] [FetchSourceCitation] [695171b1-c504-4b9f-a8b5-d230cc24fb1c] Performed FetchSourceCitation from DelayedJob(default) in 689.03ms
2015-07-11T15:16:32+0100: [Worker(delayed_job host:Malachis-MacBook-Pro.local pid:2155)] Job ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper (id=2) FAILED (0 prior attempts) with ActiveRecord::StatementInvalid: PG::ProtocolViolation: FATAL:  invalid frontend message type 1
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
: BEGIN
   (0.4ms)  BEGIN
PG::UnableToSend: no connection to the server
: BEGIN
PG::UnableToSend: no connection to the server
: UPDATE "delayed_jobs" SET "locked_by" = NULL, "locked_at" = NULL WHERE "delayed_jobs"."locked_by" = $1
PG::UnableToSend: no connection to the server
: UPDATE "delayed_jobs" SET "locked_by" = NULL, "locked_at" = NULL WHERE "delayed_jobs"."locked_by" = $1
```

If I destroy my civic-server dir and clone fresh, the problem goes away.  Any idea how I could have avoided doing that?  It sounds like a locking issue?  But not immediately obvious from the above how I would release that lock.

**Comment by acoffman** [comment]
Huh, that's an odd error message. It seems like the workers are unable to connect to postgres for some reason: 

````
PG::ProtocolViolation: FATAL:  invalid frontend message type 1
server closed the connection unexpectedly
    This probably means the server terminated abnormally
    before or while processing the request.
````

The the locking is unrelated (its just printing the query that its attempting to run), the workers lock the tasks they're working on so as not to race.

Its definitely weird though that a fresh clone fixed the issue - I would have expected you to need to bounce the database, start a new terminal session or something like that. Had you potentially installed a new version of postgres or something? I know that can occasionally make connections act oddly until you start a new terminal session.
`

**Comment by malachig** [comment]
Maybe it happens when I put my machine to sleep and wake it up again, because now I am back to the same state.  

- Have not updated anything this time for sure.  
- Its a fresh terminal session.  
- If I drop the db and recreate it using the `rake db:drop`, `rake db:create`, `rake db:schema:load`, `rake civic:import[...]` I still have the same issue,
- The error message is consistent at least

I can fire up the server (`rails s`) and client (`gulp serve`) and it seems to work and I can access view in the database.  I can also make basic edits.  But I guess since I can't start the start the background workers, some things will not work. 

- It does seem to resolve the issue if I recreate the database as follows: `rake db:drop`, `rake db:create`, `rake db:schema:load`, `rake civic:load`.  i.e. using `load` instead of `import`.

- But then I can't seem to browse that data in my local instance.  Then I get this error:
```
ActiveRecord::PendingMigrationError - 

Migrations are pending. To resolve this issue, run:

	bin/rake db:migrate RAILS_ENV=development
```

I'm going to try rebuilding from a fresh clone again and using the `import` option and see if that gets me back to a working state.

**Comment by acoffman** [comment]
Interesting - so if you use the `load` commands and then follow it up by running the suggested `rake db:migrate` command, does that result in both the background workers and the server working?

**Comment by malachig** [comment]
That also threw an error so I decided to reboot my machine and start with a fresh clone.  I was then able to reproduce the same scenario.  Which is that I can't seem to get the background workers to start except after a `civic:load`.  But then the server does not seem to be working and I get the PendingMigrationError.  

When I run `./bin/rake db:migrate RAILS_ENV=development` I see this error:

```
== 20150709222321 AddReferenceBuildToVariants: migrating ======================
-- add_column(:variants, :reference_build, :integer)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateColumn: ERROR:  column "reference_build" of relation "variants" already exists
: ALTER TABLE "variants" ADD "reference_build" integer/Users/mgriffit/git/civic/civic-server/db/migrate/20150709222321_add_reference_build_to_variants.rb:3:in `change'
ActiveRecord::StatementInvalid: PG::DuplicateColumn: ERROR:  column "reference_build" of relation "variants" already exists
: ALTER TABLE "variants" ADD "reference_build" integer
/Users/mgriffit/git/civic/civic-server/db/migrate/20150709222321_add_reference_build_to_variants.rb:3:in `change'
PG::DuplicateColumn: ERROR:  column "reference_build" of relation "variants" already exists
/Users/mgriffit/git/civic/civic-server/db/migrate/20150709222321_add_reference_build_to_variants.rb:3:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by acoffman** [comment]
Huh, so it looks like the latest migrations have already applied (its trying to add the new reference_build column, and complaining that it already exists), but for some reason it thinks that they haven't. For now, we can manually tell the database that we've run the migrations and I'll look into it further. I'm having trouble reproducing it locally.

You can open a postgres prompt directly with the following:

`psql -h localhost -d civic_development`

Then you can type the following two statements
````sql
INSERT INTO schema_migrations (version) VALUES (20150709222321);
INSERT INTO schema_migrations (version) VALUES (20150709230109);
````

Then you can type `\q` to quit the prompt. This should cause the pending migrations error to go away.

**Comment by malachig** [comment]
Ok I did that and then I was able to run `./bin/rake db:migrate RAILS_ENV=development` without error.  And then `./bin/delayed_job status` shows the background worker as running without me even having to issue the start command.  But before the migrate it did not show as running.  I have noticed this a few times and it made me wonder if the reporting the status of the background worker was not registering properly.  That being said it seems like I can generally reproduce the behavior above. Will try to summarize for clarity...

**Comment by malachig** [comment]
I repeated these to confirm the same outcomes as above.

*First method using civic:import with the txt files:*
```bash
rake db:drop #I can confirm in psql that 'civic' and 'civic_development' DBs are dropped.
rake db:create #DBs created in psql
rake db:schema:load 
rake civic:import['import/GeneSummaries.txt','import/VariantSummaries.txt','import/ClinActionEvidence.txt','import/VariantGroupSummaries.txt']
rails s
gulp serve
./bin/delayed_job start
./bin/delayed_job status  #reports 'delayed_job: no instances running'
```
In the development log I see the error above about the workers not being able to connect to postgres.  But generally the server seems to be working.

*Second method using civic:load*:
```bash
#shut down civic client and server
rake db:drop
rake db:create
rake db:schema:load
rake civic:load
rails s
gulp serve
bin/delayed_job start
bin/delayed_job status
```

Now the server is running and so are the background workers.  But if I try to browse data in the CIVIC UI it hangs and I see the 'PendingMigrationError' in the logs.  

Now I kill the CIVIC server and do this:
```
psql -h localhost -d civic_development
INSERT INTO schema_migrations (version) VALUES (20150709222321);
INSERT INTO schema_migrations (version) VALUES (20150709230109);
\q
./bin/rake db:migrate RAILS_ENV=development
```

That seems to do the trick.  Everything seems to be working and my prior issue with not being able to submit new evidence items is resolved.  :)


For my own notes, in case things get jacked while my laptop sleeps, I completed the config for my live demo as follows:
```
#Load up the website at `http://127.0.0.1:3001/` and login using github oauth credentials
rails c
User.first.make_admin!
exit
```

**Comment by malachig** [comment]
Still having trouble starting the background workers but it seems like possibly a new issue.  Now I get this error:

```
2015-07-24T14:26:54-0500: [Worker(delayed_job host:Malachis-MacBook-Pro.local pid:79282)] Starting job worker
  Delayed::Backend::ActiveRecord::Job Load (2.2ms)  UPDATE "delayed_jobs" SET locked_at = '2015-07-24 19:26:54.757795', locked_by = 'delayed_job host:Malachis-MacBook-Pro.local pid:79282' WHERE id IN (SELECT  "delayed_jobs"."id" FROM "delayed_jobs" WHERE ((run_at <= '2015-07-24 19:26:54.738488' AND (locked_at IS NULL OR locked_at < '2015-07-24 15:26:54.738574') OR locked_by = 'delayed_job host:Malachis-MacBook-Pro.local pid:79282') AND failed_at IS NULL)  ORDER BY priority ASC, run_at ASC LIMIT 1 FOR UPDATE) RETURNING *
2015-07-24T14:26:54-0500: [Worker(delayed_job host:Malachis-MacBook-Pro.local pid:79282)] Job ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper (id=3) RUNNING
  Source Load (0.4ms)  SELECT  "sources".* FROM "sources" WHERE "sources"."id" = $1 LIMIT 1  [["id", 3]]
[ActiveJob] [FetchSourceCitation] [961ca8bc-dbda-43f3-bd8b-2198d0e03a74] Performing FetchSourceCitation from DelayedJob(default) with arguments: gid://civic-server/Source/3
[ActiveJob] [FetchSourceCitation] [961ca8bc-dbda-43f3-bd8b-2198d0e03a74]    (0.9ms)  BEGIN
[ActiveJob] [FetchSourceCitation] [961ca8bc-dbda-43f3-bd8b-2198d0e03a74] PG::ProtocolViolation: FATAL:  invalid frontend message type 1
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
: BEGIN
[ActiveJob] [FetchSourceCitation] [961ca8bc-dbda-43f3-bd8b-2198d0e03a74] Performed FetchSourceCitation from DelayedJob(default) in 402.06ms
2015-07-24T14:26:55-0500: [Worker(delayed_job host:Malachis-MacBook-Pro.local pid:79282)] Job ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper (id=3) FAILED (0 prior attempts) with ActiveRecord::StatementInvalid: PG::ProtocolViolation: FATAL:  invalid frontend message type 1
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
: BEGIN
   (0.5ms)  BEGIN
PG::UnableToSend: no connection to the server
: BEGIN
PG::UnableToSend: no connection to the server
: UPDATE "delayed_jobs" SET "locked_by" = NULL, "locked_at" = NULL WHERE "delayed_jobs"."locked_by" = $1
PG::UnableToSend: no connection to the server
: UPDATE "delayed_jobs" SET "locked_by" = NULL, "locked_at" = NULL WHERE "delayed_jobs"."locked_by" = $1
```

**Comment by acoffman** [comment]
So, this was a bit of a crazy bug (never great when your own issue is the first google result for an error message). As best as I can tell, it seems that somehow the serialization format for background jobs must have gotten changed between versions (which shouldn't have happened), or somehow you ended up with a corrupted job in the database. If you open up your console with `rails c` and then type `Delayed::Job.all.each { |j| j.delete }` close your console, and then try to boot up the background worker, it should work. I was finally able to replicate this locally and that fixed it. At that point, submitting a new evidence item should trigger the expected background processing.

**Comment by malachig** [comment]
This did work for me!  Thanks for the forensic analysis @acoffman . :)

**Comment by malachig** [comment]
It's weird, I am still able to reproduce this error quite consistently.  The `Delayed::Job.all.each { |j| j.delete }` seems to work but if I drop the DB and repopulate it I wind up back in the same spot.

**Comment by acoffman** [comment]
That is weird - maybe the corruption is in the database dump itself? Though that wouldn't explain why its not happening for everyone. I will push a new database image up this afternoon and see if that fixes it for you more permanently.
