### ISSUE TITLE
Data releases not intuitive

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-server#72]
The current "Data releases" page has a single link for "Nightly" dump of each of Gene, Variant, ClinicalEvidence, and VariantGroup data. Can we incorporate a date into the file name so that if someone downloads subsequent versions there is a way to distinguish them from each other. Also, I thought there was a plan to also had weekly or monthly releases that stack up and act as "freezes" of the dataset.

**Comment by acoffman** [comment]
We should have all of the above working - but you are correct that they aren't appearing on the site! I will take a look.

**Comment by acoffman** [comment]
These should now be working as expected. Not resolving quite yet as I don't have the dates in the filenames yet.

**Comment by acoffman** [comment]
From the next data dump on, downloaded files will include either "nightly" or the date generated in the filename.
