### ISSUE TITLE
Login to admin console from public site resolves to "http://127.0.0.1:3000/admin" 

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#74]
When I am logged into the public instance of civic and attempt to login to the admin console it attempts (and fails) to reach http://127.0.0.1:3000/admin.

**Comment by malachig** [comment]
@jmcmichael this might have been a client issue.  Wasn't quite sure when I submitted it.

**Comment by acoffman** [comment]
Fixed in the new build process!
