### ISSUE TITLE
Duplicate entries in public instance

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#75]
It seems like there are some duplicate entries:

For example:
https://civic.genome.wustl.edu/#/events/genes/57/summary/variants/154/summary/evidence/409/summary
https://civic.genome.wustl.edu/#/events/genes/57/summary/variants/154/summary/evidence/410/summary

These two entries seem identical except that one is created by 'admin' and the other by 'rbilski'.

**Comment by malachig** [comment]
Wondering if this was somehow introduced when backfilling ownership of evidence items.

**Comment by acoffman** [comment]
Yeah, these were introduced during the backfill. The duplicates have been removed - with precedence given to Evidence Items that had a "real" curator.
