### ISSUE TITLE
Variants with no evidence statements (or at least none that display) in public instance

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#76]
See this example:
https://civic.genome.wustl.edu/#/events/genes/65/summary/variants/168/summary

In the browse table we can see that BTK is supposed to have 1 evidence statement.  But when we click on C481S I don't see anything in the evidence statement grid.

**Comment by malachig** [comment]
REL EXPRESSION is another example:

https://civic.genome.wustl.edu/#/events/genes/57/summary/variants/162/summary

**Comment by malachig** [comment]
Here is another example, BCL2 LOSS-OF-FUNCTION does not have any evidence statements.

**Comment by acoffman** [comment]
This should be fixed now!
