### ISSUE TITLE
Some evidence statements still appear under user "Admin"

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-server#77]
Do we know why some evidence statements still appear as last modified by Admin despite showing as being created by a specific user in the spreadsheet? Here is just one example. I was able to find several.
https://civic.genome.wustl.edu/#/events/genes/18/summary/variants/32/summary/evidence/4/summary

**Comment by acoffman** [comment]
Yeah, I talked about it briefly in the meeting on Wednesday, but its basically instances where what's on the site has diverged from what's in the spreadsheet. For instance, in that example, the statement text doesn't exist in the spreadsheet. I did some work last week and this weekend that should let me match up items that have diverged based on their edit history and allow for a more complete backfill, so these instances should be largely eliminated in the next day or so.

**Comment by obigriffith** [comment]
Ah right. I remember now.

**Comment by acoffman** [comment]
Fixed in the new build process!

**Comment by acoffman** [comment]
Wrong issue.

**Comment by malachig** [comment]
Just checking in on this one.  In the latest public version, many evidence items no longer show "Admin", but these now show nothing at all.

![screen shot 2015-12-23 at 11 26 06 am](https://cloud.githubusercontent.com/assets/856728/11981423/ff5700e2-a967-11e5-8a6a-2198a55dc293.png)

**Comment by malachig** [comment]
On the other hand, variant summaries do show who last modified them, but almost all show "Created by Admin".

**Comment by acoffman** [comment]
All Evidence Items should now have both a submitted by and an accepted by! Admin is still cropping up in some of the variant and gene summaries and I'm taking a look at that now.
