### ISSUE TITLE
Add evidence statement currently does not populate variant/gene and can't be accepted

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-server#78]
I just added a new evidence statement for an existing variant (DNAJB1-PRKACA) and gene (PRKACA) in the public/live interface. When I finished entering all details I got a successful thank you from the front end. It would be nice if this offered a link to navigate to where this new statement appears (in pending status). 

I then went to admin interface and do see my new evidence statement but the variant and gene data are not present and I do not have an option to accept the new statement.
![screen shot 2015-07-28 at 6 47 41 pm](https://cloud.githubusercontent.com/assets/1638042/8946867/18829d88-355a-11e5-92f8-5ce835fd7e1e.png)
![screen shot 2015-07-28 at 6 51 41 pm](https://cloud.githubusercontent.com/assets/1638042/8946868/188396a2-355a-11e5-93e0-b42a50a32e50.png)

**Comment by malachig** [comment]
Right now I see two evidence statements with a failed status:
https://civic.genome.wustl.edu/admin/evidence_items/437
https://civic.genome.wustl.edu/admin/evidence_items/438

If the problem that caused these to fail has been fixed maybe we could manually patch them now?  Or delete and recreate?

**Comment by acoffman** [comment]
These have been manually patched and the underlying issues are resolved.
