### ISSUE TITLE
Unable to change correct disease

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-server#80]
Not sure if this is front end or backend. But, I am unable to change the disease ID for this evidence statement:
https://civic.genome.wustl.edu/#/events/genes/25/summary/variants/57/summary/evidence/301/summary

The doid should be 3908 instead of 3909. When I edit evidence I see both "Disease" and "Disease ID" fields. I tried editing both the Disease ID to 3908 and the Disease to Non-small Cell Lung Carcinoma along with some other edits (pubmed and evidence level). The latter edits took but the disease ID revision did not appear. Now when I just trying changing the Disease and/or Disease ID I get a "409 - The attempted update conflicts with an existing record." error. Its like it is not recognizing this as a valid revision.

**Comment by acoffman** [comment]
This is fixed in master!
