### ISSUE TITLE
different results from variants/typeahead_results and datatables/variants endpoints

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-server#81]
The gene MGMT shows up in the datatables/variants endpoint, but not the variants/typeahead endpoint.

http://127.0.0.1:3001/api/variants/typeahead_results?limit=12&query=MGMT

vs

http://127.0.0.1:3001/api/datatables/variants?count=0&filter%5Bentrez_gene%5D=MGMT&page=1&sorting%5Bvariant%5D=asc

(genome/civic-client#120 depends on this)

**Comment by acoffman** [comment]
Fixed in master!
