### ISSUE TITLE
Genes endpoint in API does not contain all the genes

### ISSUE THREAD

**Issue by Shane-Neeley** [genome/civic-server#82]
For example, the website lists PIK3CA variants, but the general genes endpoint doesn't mention PIK3CA.

https://civic.genome.wustl.edu/api/genes/

Something I'm missing? Thank you.

Shane

**Comment by acoffman** [comment]
This is something we have actually just been discussing internally, so you have good timing. The "index" style endpoints are paginated, you don't get every single result back. You can manipulate the number of entries returned with the `count` parameter, and the page of results with the `page` parameter. We will soon be adding some additional fields (such as current page size, total number of pages, and total number of results) that should help users navigate the results more easily (and inform them of the pagination in the first place.)

I will update this issue when those changes go live!

**Comment by Shane-Neeley** [comment]
Thanks Adam! I'll use the count parameter.

**Comment by obigriffith** [comment]
A current issue is that if you set count to some large number (e.g., 1000), hoping to just get all genes currently in CIViC you get a whole bunch of genes with no variants that aren't really CIViC genes since we are now pre-loading all entrez genes in the backend but only displaying genes with at least one variant on the front end. The latter makes sense but there is a mismatch with the genes API endpoint as documented.

**Comment by Shane-Neeley** [comment]
Thanks, good to know! I was using a large count parameter, but I can just start filtering by my own genes of interest. Though something like a count of 50,000 would catch all the entrez genes right? I'm afraid that might be too much for the server though.

**Comment by malachig** [comment]
I have been doing some queries with count=100,000 and it seems to work surprisingly fast.  That should catch all Entrez genes:
```
wget ftp://ftp.ncbi.nih.gov/gene/DATA/GENE_INFO/Mammalia/Homo_sapiens.gene_info.gz && gzcat Homo_sapiens.gene_info.gz && gzcat Homo_sapiens.gene_info.gz | cut -f 2 | sort | uniq | wc -l
```
Currently 59557 human genes in Entrez.

**Comment by acoffman** [comment]
Improved documentation has gone out which should help clarify much of this. We will continue to improve the docs and provide more examples as we go forward!
