### ISSUE TITLE
Variant Group Edit POST returns 500 error

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-server#87]
I've tried editing each field in in the Variant Group Edit page, and the server returns a 500 error for each of them:

NameError at /api/variant_groups/15/suggested_changes
> undefined local variable or method `new_drugs' for #<VariantGroup:0x007fbc74ae9880>

app/models/variant_group.rb, line 24:
``` ruby
   19       if changes[:variants].blank?
   20         {}
   21       else
   22         new_variants = get_variants_from_list(changes[:variants].reject(&:blank?)).map(&:id).sort.uniq
   23         existing_variants = self.variants.map(&:id).sort.uniq
>  24         if new_drugs == existing_variants
   25           {}
   26         else
   27           {
   28             variant_ids: [existing_variants, new_variants]
   29           }
```

**Comment by acoffman** [comment]
This should now be fixed in master!
