### ISSUE TITLE
Some genes list no Gene Aliases but it seems like they do have synonyms

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#89]
For example:
KMT2D and BTK both have many synonyms but in the gene view for these genes none are showing...

**Comment by malachig** [comment]
It always throws me when I look at the browse by gene data-grid and there is not alias for KMT2D.  This gene has a lot of aliases.  And they appear in the MyGene.info results on the Gene page for KMT2D.  Just not in the browse by gene data grid.

**Comment by acoffman** [comment]
It seems like some of these didn't fill in correctly from MyGene.info. I'm running the scraper again and it appears to be working. (For instance, the two you mentioned now have aliases). There were ~20,000 genes with no aliases populated, so it will take a little bit for it to run, but I'll keep an eye on it!
