### ISSUE TITLE
Variant type parameter

### ISSUE THREAD

**Issue by bainscou** [genome/civic-server#95]
Along with all of the chromosomal and mutation information that has recently been added to CIViC, I think that it would be good to have a mutation type parameter (Such as SNV, INDEL, Amplification). We could potentially use the Sequence Ontology for such a purpose.

An example use case would be a syncing with DoCM. Since DoCM only supports snvs and indels at this time it would be nice to query CIViC only for those types of events.

**Comment by obigriffith** [comment]
Yeah. This is definitely something we should do. First step would be to see if all the existing variant/event types in CIViC can be described by SO or an other option.

**Comment by malachig** [comment]
Perhaps using the sequence ontology:
http://www.sequenceontology.org/browser/obob.cgi
http://bioportal.bioontology.org/ontologies/SO

Or VariO perhaps:
http://variationontology.org/

**Comment by acoffman** [comment]
Slightly more up-to-date discussion of this has been had on #102. I'm going to go ahead and close this one as a duplicate.
