### ISSUE TITLE
Unable to submit new evidence

### ISSUE THREAD

**Issue by pondycrane** [genome/civic-server#98]
I'd like to submit new evidence, but the following error occurred: "500 - The CIViC server experienced an unrecoverable error, please check the console output for more information."

**Comment by acoffman** [comment]
Can you tell me more about the evidence item you're attempting to submit? That would help with reproducing the error so I can fix it!

**Comment by acoffman** [comment]
We have exercised this form fairly thoroughly and are unable to make it fail. I am going to resolve this, but if you encounter this error again, or recall what you were trying to do when it failed, please do let us know! 

Thanks!
